export const FINLAND_TICKERS = [
  "HRTIS",
  "HX5020GI",
  "HX502060GI",
  "ICP1V",
  "HX302020PI",
  "BITTI",
  "OMXH25GI",
  "KEMPOWR",
  "VAIAS",
  "KAMUX",
  "BONEH",
  "HX402040PI",
  "HX30GI",
  "HX601010GI",
  "TAMTRON",
  "LEHTO",
  "DOV1V",
  "SANOMA",
  "EVLI",
  "DWF",
  "REMEDYEW118",
  "TYRES",
  "FIA1S",
  "PAMPALO",
  "EEZY",
  "TNOM",
  "ERIBR",
  "HX3020PI",
  "TIETO",
  "RAIVV",
  "HX303020GI",
  "NIXU",
  "HX30PI",
  "SUY1V",
  "HX551010GI",
  "HX302010GI",
  "PURMO",
  "AFAGR",
  "HX402030GI",
  "ORNBV",
  "PIIPPO",
  "DETEC",
  "HX4050PI",
  "HX4520GI",
  "STEAV",
  "PON1V",
  "ACG1V",
  "PALLAS",
  "OMXHPI",
  "REMEDYEW119",
  "KESKOB",
  "ALBAV",
  "SPINN",
  "APETIT",
  "OMXH25EXP",
  "ORTHEX",
  "HEALTH",
  "ROVIO",
  "HX3010GI",
  "HX4040PI",
  "KREATE",
  "TEM1V",
  "HEEROS",
  "HX3030GI",
  "HX502030GI",
  "HX201020GI",
  "IFA1V",
  "HX4010PI",
  "VERK",
  "HX651030PI",
  "CTH1V",
  "HKSAV",
  "SPRING",
  "PUMU",
  "HX20GI",
  "SITOWS",
  "FIA1SU0123",
  "EXL1V",
  "ALBBV",
  "FSKRS",
  "OMXH25ESGGI",
  "RAIKV",
  "HX5510GI",
  "LL1SPAC",
  "HX65PI",
  "HX5520GI",
  "OPTOMED",
  "OMXHCAPGI",
  "HX502030PI",
  "HX402040GI",
  "FIFAX",
  "AIFORIA",
  "HX55GI",
  "LOIHDE",
  "TOIVO",
  "CGCBV",
  "HX402030PI",
  "WETTERI",
  "BETOLAR",
  "HX55PI",
  "ATRAV",
  "HX40PI",
  "HX5020PI",
  "HX45GI",
  "QPR1V",
  "HX351010GI",
  "NOKIA",
  "HX3030PI",
  "YIT",
  "METSB",
  "OUT1V",
  "HX4040GI",
  "HX551020PI",
  "KOSKI",
  "KSLAV",
  "DIGIGR",
  "HX15GI",
  "HX351010PI",
  "SIILI",
  "DIGIA",
  "TRH1V",
  "TLT1V",
  "VIAFIN",
  "HX601010PI",
  "SCANFL",
  "HX101010GI",
  "OMXHSCPI",
  "TOKMAN",
  "EAGLE",
  "HX60GI",
  "HX404010GI",
  "HX45PI",
  "LEMON",
  "OMXSUSTFICAPPI",
  "INDERES",
  "HX101020GI",
  "FODELIA",
  "HX404010PI",
  "WUF1V",
  "FSECURE",
  "MUSTI",
  "SOSI1",
  "LEADD",
  "HX551030GI",
  "OMXSUSTAINFIPI",
  "RELAIS",
  "NOHO",
  "HX502060PI",
  "TULAV",
  "HX20PI",
  "OMXH25ESGNI",
  "NETUM",
  "EQV1VEW122",
  "BIOBV",
  "HX201030PI",
  "HX5010GI",
  "HX303020PI",
  "TTALO",
  "HX451010PI",
  "HX201020PI",
  "STERV",
  "AKTIA",
  "CAPMAN",
  "OMXHMCGI",
  "HX551030PI",
  "ADMCM",
  "HX451020PI",
  "GOFORE",
  "OMXHLCGI",
  "FONDIA",
  "ADMIN",
  "HX302020GI",
  "OMXH15NI",
  "SOLWERS",
  "OMXSUSTAINFIGI",
  "HX151010PI",
  "ECOUP",
  "OMXHBCAPPI",
  "HX551010PI",
  "ALEX",
  "OMXHLCPI",
  "TELIA1",
  "ANORA",
  "SSABAH",
  "VIK1V",
  "HX65GI",
  "CTY1S",
  "VALOE",
  "OMXH15GI",
  "INVEST",
  "UNITED",
  "SOLTEQ",
  "HARVIA",
  "METSA",
  "ASUNTO",
  "OMASP",
  "ELISA",
  "OMXHSCGI",
  "HX5510PI",
  "CONSTI",
  "OMXH25ESG",
  "METSO",
  "HONBS",
  "OMXHBGI",
  "AALLON",
  "HX651010PI",
  "HX10GI",
  "SAGCV",
  "OMXHBPI",
  "HX35PI",
  "HX15PI",
  "NYAB",
  "HX502050PI",
  "KNEBV",
  "WRT1V",
  "HX4010GI",
  "KOJAMO",
  "HX3020GI",
  "KELAS",
  "ARVOSK",
  "BOREO",
  "FARON",
  "HX60PI",
  "OKDBV",
  "QTCOM",
  "OMXH25",
  "HX4020GI",
  "HX402020PI",
  "FORTUM",
  "HX651010GI",
  "SLG OMXH25",
  "ALISA",
  "SSH1V",
  "HX4050GI",
  "HX5010PI",
  "HX201010GI",
  "REMEDY",
  "NANOFH",
  "HX151010GI",
  "ILKKA1",
  "ELEAV",
  "HX40GI",
  "OLVAS",
  "LAPWALL",
  "SAMPO",
  "HX5520PI",
  "WITH",
  "WITTED",
  "BRETEC",
  "HX402020GI",
  "MARAS",
  "UPONOR",
  "ENENTO",
  "HUH1V",
  "OVARO",
  "NXTMH",
  "HX4030PI",
  "GLA1V",
  "HX50PI",
  "HX35GI",
  "ETTE",
  "HX201010PI",
  "HX302010PI",
  "OMXSUSTFICAPGI",
  "MODU",
  "HX4030GI",
  "HX4510PI",
  "HX50GI",
  "VINCIT",
  "TITAN",
  "HX651030GI",
  "HX10PI",
  "HX4020PI",
  "DUELL",
  "HX502040GI",
  "VALMT",
  "RAUTE",
  "NESTE",
  "REG1V",
  "TAALA",
  "PNA1V",
  "OMXHBCAPGI",
  "HX551020GI",
  "HX3010PI",
  "HX451010GI",
  "MERIH",
  "OMXHCAPPI",
  "RUSH",
  "HX4510GI",
  "KESKOA",
  "KCR",
  "NLG1V",
  "CAV1V",
  "HX4520PI",
  "HX502020GI",
  "EQV1V",
  "OMXH25ER",
  "SRV1V",
  "ILKKA2",
  "PIHLIS",
  "OMXH15",
  "LAMOR",
  "HX201030GI",
  "HX451020GI",
  "NORRH",
  "HX502040PI",
  "KEMIRA",
  "NDA FI",
  "EFECTE",
  "REKA",
  "HX502020PI",
  "MEKKO",
  "UPM",
  "PARTNE1",
  "ORNAV",
  "TALLINK",
  "HX151020GI",
  "LAT1V",
  "HX502050GI",
  "FIA1SN0123",
  "HX101020PI",
  "RAP1V",
  "ESENSE",
  "ASPO",
  "PUUILO",
  "ALMA",
  "KHG",
  "ROBIT",
  "OMXH25DVP",
  "STOCKA",
  "MANTA",
  "OMXHGI",
  "OMXHMCPI",
  "HX101010PI",
  "HX151020PI",
  "OKDAV",
  "MERUS",
  "SSABBH",
];

export const FINLAND_FEED = [
  {
    fullName: null,
    feed: 100,
    ticker: "HRTIS",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 100,
    ticker: "HX5020GI",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 100,
    ticker: "HX502060GI",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 100,
    ticker: "ICP1V",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 100,
    ticker: "HX302020PI",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 100,
    ticker: "BITTI",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 100,
    ticker: "OMXH25GI",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 100,
    ticker: "KEMPOWR",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 100,
    ticker: "VAIAS",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 100,
    ticker: "KAMUX",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 100,
    ticker: "BONEH",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 100,
    ticker: "HX402040PI",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 100,
    ticker: "HX30GI",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 100,
    ticker: "HX601010GI",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 100,
    ticker: "TAMTRON",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 100,
    ticker: "LEHTO",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 100,
    ticker: "DOV1V",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 100,
    ticker: "SANOMA",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 100,
    ticker: "EVLI",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 100,
    ticker: "DWF",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 100,
    ticker: "REMEDYEW118",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 100,
    ticker: "TYRES",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 100,
    ticker: "FIA1S",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 100,
    ticker: "PAMPALO",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 100,
    ticker: "EEZY",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 100,
    ticker: "TNOM",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 100,
    ticker: "ERIBR",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 100,
    ticker: "HX3020PI",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 100,
    ticker: "TIETO",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 100,
    ticker: "RAIVV",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 100,
    ticker: "HX303020GI",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 100,
    ticker: "NIXU",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 100,
    ticker: "HX30PI",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 100,
    ticker: "SUY1V",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 100,
    ticker: "HX551010GI",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 100,
    ticker: "HX302010GI",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 100,
    ticker: "PURMO",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 100,
    ticker: "AFAGR",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 100,
    ticker: "HX402030GI",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 100,
    ticker: "ORNBV",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 100,
    ticker: "PIIPPO",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 100,
    ticker: "DETEC",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 100,
    ticker: "HX4050PI",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 100,
    ticker: "HX4520GI",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 100,
    ticker: "STEAV",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 100,
    ticker: "PON1V",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 100,
    ticker: "ACG1V",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 100,
    ticker: "PALLAS",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 100,
    ticker: "OMXHPI",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 100,
    ticker: "REMEDYEW119",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 100,
    ticker: "KESKOB",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 100,
    ticker: "ALBAV",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 100,
    ticker: "SPINN",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 100,
    ticker: "APETIT",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 100,
    ticker: "OMXH25EXP",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 100,
    ticker: "ORTHEX",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 100,
    ticker: "HEALTH",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 100,
    ticker: "ROVIO",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 100,
    ticker: "HX3010GI",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 100,
    ticker: "HX4040PI",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 100,
    ticker: "KREATE",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 100,
    ticker: "TEM1V",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 100,
    ticker: "HEEROS",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 100,
    ticker: "HX3030GI",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 100,
    ticker: "HX502030GI",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 100,
    ticker: "HX201020GI",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 100,
    ticker: "IFA1V",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 100,
    ticker: "HX4010PI",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 100,
    ticker: "VERK",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 100,
    ticker: "HX651030PI",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 100,
    ticker: "CTH1V",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 100,
    ticker: "HKSAV",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 100,
    ticker: "SPRING",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 100,
    ticker: "PUMU",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 100,
    ticker: "HX20GI",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 100,
    ticker: "SITOWS",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 100,
    ticker: "FIA1SU0123",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 100,
    ticker: "EXL1V",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 100,
    ticker: "ALBBV",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 100,
    ticker: "FSKRS",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 100,
    ticker: "OMXH25ESGGI",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 100,
    ticker: "RAIKV",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 100,
    ticker: "HX5510GI",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 100,
    ticker: "LL1SPAC",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 100,
    ticker: "HX65PI",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 100,
    ticker: "HX5520GI",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 100,
    ticker: "OPTOMED",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 100,
    ticker: "OMXHCAPGI",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 100,
    ticker: "HX502030PI",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 100,
    ticker: "HX402040GI",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 100,
    ticker: "FIFAX",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 100,
    ticker: "AIFORIA",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 100,
    ticker: "HX55GI",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 100,
    ticker: "LOIHDE",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 100,
    ticker: "TOIVO",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 100,
    ticker: "CGCBV",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 100,
    ticker: "HX402030PI",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 100,
    ticker: "WETTERI",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 100,
    ticker: "BETOLAR",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 100,
    ticker: "HX55PI",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 100,
    ticker: "ATRAV",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 100,
    ticker: "HX40PI",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 100,
    ticker: "HX5020PI",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 100,
    ticker: "HX45GI",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 100,
    ticker: "QPR1V",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 100,
    ticker: "HX351010GI",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 100,
    ticker: "NOKIA",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 100,
    ticker: "HX3030PI",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 100,
    ticker: "YIT",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 100,
    ticker: "METSB",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 100,
    ticker: "OUT1V",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 100,
    ticker: "HX4040GI",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 100,
    ticker: "HX551020PI",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 100,
    ticker: "KOSKI",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 100,
    ticker: "KSLAV",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 100,
    ticker: "DIGIGR",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 100,
    ticker: "HX15GI",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 100,
    ticker: "HX351010PI",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 100,
    ticker: "SIILI",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 100,
    ticker: "DIGIA",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 100,
    ticker: "TRH1V",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 100,
    ticker: "TLT1V",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 100,
    ticker: "VIAFIN",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 100,
    ticker: "HX601010PI",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 100,
    ticker: "SCANFL",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 100,
    ticker: "HX101010GI",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 100,
    ticker: "OMXHSCPI",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 100,
    ticker: "TOKMAN",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 100,
    ticker: "EAGLE",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 100,
    ticker: "HX60GI",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 100,
    ticker: "HX404010GI",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 100,
    ticker: "HX45PI",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 100,
    ticker: "LEMON",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 100,
    ticker: "OMXSUSTFICAPPI",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 100,
    ticker: "INDERES",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 100,
    ticker: "HX101020GI",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 100,
    ticker: "FODELIA",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 100,
    ticker: "HX404010PI",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 100,
    ticker: "WUF1V",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 100,
    ticker: "FSECURE",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 100,
    ticker: "MUSTI",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 100,
    ticker: "SOSI1",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 100,
    ticker: "LEADD",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 100,
    ticker: "HX551030GI",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 100,
    ticker: "OMXSUSTAINFIPI",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 100,
    ticker: "RELAIS",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 100,
    ticker: "NOHO",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 100,
    ticker: "HX502060PI",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 100,
    ticker: "TULAV",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 100,
    ticker: "HX20PI",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 100,
    ticker: "OMXH25ESGNI",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 100,
    ticker: "NETUM",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 100,
    ticker: "EQV1VEW122",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 100,
    ticker: "BIOBV",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 100,
    ticker: "HX201030PI",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 100,
    ticker: "HX5010GI",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 100,
    ticker: "HX303020PI",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 100,
    ticker: "TTALO",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 100,
    ticker: "HX451010PI",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 100,
    ticker: "HX201020PI",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 100,
    ticker: "STERV",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 100,
    ticker: "AKTIA",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 100,
    ticker: "CAPMAN",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 100,
    ticker: "OMXHMCGI",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 100,
    ticker: "HX551030PI",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 100,
    ticker: "ADMCM",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 100,
    ticker: "HX451020PI",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 100,
    ticker: "GOFORE",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 100,
    ticker: "OMXHLCGI",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 100,
    ticker: "FONDIA",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 100,
    ticker: "ADMIN",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 100,
    ticker: "HX302020GI",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 100,
    ticker: "OMXH15NI",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 100,
    ticker: "SOLWERS",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 100,
    ticker: "OMXSUSTAINFIGI",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 100,
    ticker: "HX151010PI",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 100,
    ticker: "ECOUP",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 100,
    ticker: "OMXHBCAPPI",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 100,
    ticker: "HX551010PI",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 100,
    ticker: "ALEX",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 100,
    ticker: "OMXHLCPI",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 100,
    ticker: "TELIA1",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 100,
    ticker: "ANORA",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 100,
    ticker: "SSABAH",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 100,
    ticker: "VIK1V",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 100,
    ticker: "HX65GI",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 100,
    ticker: "CTY1S",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 100,
    ticker: "VALOE",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 100,
    ticker: "OMXH15GI",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 100,
    ticker: "INVEST",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 100,
    ticker: "UNITED",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 100,
    ticker: "SOLTEQ",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 100,
    ticker: "HARVIA",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 100,
    ticker: "METSA",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 100,
    ticker: "ASUNTO",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 100,
    ticker: "OMASP",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 100,
    ticker: "ELISA",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 100,
    ticker: "OMXHSCGI",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 100,
    ticker: "HX5510PI",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 100,
    ticker: "CONSTI",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 100,
    ticker: "OMXH25ESG",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 100,
    ticker: "METSO",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 100,
    ticker: "HONBS",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 100,
    ticker: "OMXHBGI",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 100,
    ticker: "AALLON",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 100,
    ticker: "HX651010PI",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 100,
    ticker: "HX10GI",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 100,
    ticker: "SAGCV",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 100,
    ticker: "OMXHBPI",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 100,
    ticker: "HX35PI",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 100,
    ticker: "HX15PI",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 100,
    ticker: "NYAB",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 100,
    ticker: "HX502050PI",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 100,
    ticker: "KNEBV",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 100,
    ticker: "WRT1V",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 100,
    ticker: "HX4010GI",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 100,
    ticker: "KOJAMO",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 100,
    ticker: "HX3020GI",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 100,
    ticker: "KELAS",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 100,
    ticker: "ARVOSK",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 100,
    ticker: "BOREO",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 100,
    ticker: "FARON",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 100,
    ticker: "HX60PI",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 100,
    ticker: "OKDBV",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 100,
    ticker: "QTCOM",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 100,
    ticker: "OMXH25",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 100,
    ticker: "HX4020GI",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 100,
    ticker: "HX402020PI",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 100,
    ticker: "FORTUM",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 100,
    ticker: "HX651010GI",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 100,
    ticker: "SLG OMXH25",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 100,
    ticker: "ALISA",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 100,
    ticker: "SSH1V",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 100,
    ticker: "HX4050GI",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 100,
    ticker: "HX5010PI",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 100,
    ticker: "HX201010GI",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 100,
    ticker: "REMEDY",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 100,
    ticker: "NANOFH",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 100,
    ticker: "HX151010GI",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 100,
    ticker: "ILKKA1",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 100,
    ticker: "ELEAV",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 100,
    ticker: "HX40GI",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 100,
    ticker: "OLVAS",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 100,
    ticker: "LAPWALL",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 100,
    ticker: "SAMPO",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 100,
    ticker: "HX5520PI",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 100,
    ticker: "WITH",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 100,
    ticker: "WITTED",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 100,
    ticker: "BRETEC",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 100,
    ticker: "HX402020GI",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 100,
    ticker: "MARAS",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 100,
    ticker: "UPONOR",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 100,
    ticker: "ENENTO",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 100,
    ticker: "HUH1V",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 100,
    ticker: "OVARO",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 100,
    ticker: "NXTMH",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 100,
    ticker: "HX4030PI",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 100,
    ticker: "GLA1V",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 100,
    ticker: "HX50PI",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 100,
    ticker: "HX35GI",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 100,
    ticker: "ETTE",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 100,
    ticker: "HX201010PI",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 100,
    ticker: "HX302010PI",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 100,
    ticker: "OMXSUSTFICAPGI",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 100,
    ticker: "MODU",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 100,
    ticker: "HX4030GI",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 100,
    ticker: "HX4510PI",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 100,
    ticker: "HX50GI",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 100,
    ticker: "VINCIT",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 100,
    ticker: "TITAN",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 100,
    ticker: "HX651030GI",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 100,
    ticker: "HX10PI",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 100,
    ticker: "HX4020PI",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 100,
    ticker: "DUELL",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 100,
    ticker: "HX502040GI",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 100,
    ticker: "VALMT",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 100,
    ticker: "RAUTE",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 100,
    ticker: "NESTE",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 100,
    ticker: "REG1V",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 100,
    ticker: "TAALA",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 100,
    ticker: "PNA1V",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 100,
    ticker: "OMXHBCAPGI",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 100,
    ticker: "HX551020GI",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 100,
    ticker: "HX3010PI",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 100,
    ticker: "HX451010GI",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 100,
    ticker: "MERIH",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 100,
    ticker: "OMXHCAPPI",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 100,
    ticker: "RUSH",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 100,
    ticker: "HX4510GI",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 100,
    ticker: "KESKOA",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 100,
    ticker: "KCR",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 100,
    ticker: "NLG1V",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 100,
    ticker: "CAV1V",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 100,
    ticker: "HX4520PI",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 100,
    ticker: "HX502020GI",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 100,
    ticker: "EQV1V",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 100,
    ticker: "OMXH25ER",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 100,
    ticker: "SRV1V",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 100,
    ticker: "ILKKA2",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 100,
    ticker: "PIHLIS",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 100,
    ticker: "OMXH15",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 100,
    ticker: "LAMOR",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 100,
    ticker: "HX201030GI",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 100,
    ticker: "HX451020GI",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 100,
    ticker: "NORRH",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 100,
    ticker: "HX502040PI",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 100,
    ticker: "KEMIRA",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 100,
    ticker: "NDA FI",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 100,
    ticker: "EFECTE",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 100,
    ticker: "REKA",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 100,
    ticker: "HX502020PI",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 100,
    ticker: "MEKKO",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 100,
    ticker: "UPM",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 100,
    ticker: "PARTNE1",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 100,
    ticker: "ORNAV",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 100,
    ticker: "TALLINK",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 100,
    ticker: "HX151020GI",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 100,
    ticker: "LAT1V",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 100,
    ticker: "HX502050GI",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 100,
    ticker: "FIA1SN0123",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 100,
    ticker: "HX101020PI",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 100,
    ticker: "RAP1V",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 100,
    ticker: "ESENSE",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 100,
    ticker: "ASPO",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 100,
    ticker: "PUUILO",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 100,
    ticker: "ALMA",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 100,
    ticker: "KHG",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 100,
    ticker: "ROBIT",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 100,
    ticker: "OMXH25DVP",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 100,
    ticker: "STOCKA",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 100,
    ticker: "MANTA",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 100,
    ticker: "OMXHGI",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 100,
    ticker: "OMXHMCPI",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 100,
    ticker: "HX101010PI",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 100,
    ticker: "HX151020PI",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 100,
    ticker: "OKDAV",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 100,
    ticker: "MERUS",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 100,
    ticker: "SSABBH",
    isin: null,
    mic: null,
    currency: null,
  },
];
