export const NORWAY_TICKERS = [
  "2020",
  "OSEXP",
  "AEGA",
  "NTG",
  "ABL",
  "SATS",
  "PHLY",
  "JAREN",
  "KMCP",
  "SASNO",
  "BGBIO",
  "ENSU",
  "RANA",
  "SSG",
  "NHY",
  "OCEAN",
  "AKVA",
  "OCDN",
  "OBSHX",
  "OBX",
  "OSEMN",
  "HELG",
  "IOX",
  "LEA",
  "OBXUP",
  "BALT",
  "CSS",
  "SKAND",
  "CIRCA",
  "SCHB",
  "SBO",
  "NOD",
  "AKOBO",
  "ECIT",
  "BOR",
  "ARGEO",
  "OTECG",
  "OBSHP",
  "HAUTO",
  "B2I",
  "CLOUD",
  "BGBIS",
  "GOD",
  "SB68",
  "ROMSB",
  "BWIDL",
  "OSEAP",
  "SNOR",
  "SUNSB",
  "YAR",
  "REACH",
  "AUSS",
  "KYOTO",
  "TYSB",
  "ENDUR",
  "OSEFP",
  "OAAXN",
  "ELABS",
  "AFK",
  "OBXEP",
  "KOG",
  "EXTX",
  "OBXD",
  "BWO",
  "BONHR",
  "LINK",
  "ASTK",
  "ASA",
  "SAGA",
  "OTECP",
  "IFISH",
  "OREG",
  "SOAG",
  "WWI",
  "MPCES",
  "MORG",
  "VAR",
  "SACAM",
  "ODL",
  "SVEG",
  "OSEER",
  "NKR",
  "OTS",
  "POL",
  "AYFIE",
  "SNI",
  "NAPA",
  "PHO",
  "SHLF",
  "DDRIL",
  "SBX",
  "NSOL",
  "HYN",
  "SOR",
  "NORDH",
  "STSU",
  "RING",
  "OUTG",
  "AURA",
  "TOTG",
  "SPOG",
  "RISH",
  "AMSC",
  "MULTI",
  "OKEA",
  "OBOSP",
  "AGLX",
  "BWE",
  "OSEAN",
  "OBSFP",
  "OREN",
  "BAKKA",
  "OSEEX",
  "PRS",
  "ACC",
  "ENTRA",
  "EQVA",
  "PYRUM",
  "HSHP",
  "OSEFX",
  "STATT",
  "WSTEP",
  "OBMN",
  "ROMER",
  "GENT",
  "ISLAX",
  "SOFF",
  "MVE",
  "SMCRT",
  "ANDF",
  "ACR",
  "ALNG",
  "OSUN",
  "FRO",
  "NORAM",
  "AIRX",
  "AURG",
  "OUTP",
  "TIETO",
  "SCHA",
  "GIGA",
  "SPOT",
  "KID",
  "ADE",
  "HYPRO",
  "PEXIP",
  "OSEBS",
  "NSKOG",
  "SRBNK",
  "SSSFX",
  "ASTRO",
  "MNTR",
  "OET",
  "HAV",
  "NBX",
  "BSP",
  "OLT",
  "SMOP",
  "AKH",
  "ULTI",
  "BMA",
  "GEOS",
  "SALM",
  "HSPG",
  "FLNG",
  "CYVIZ",
  "NYKD",
  "OBXES",
  "OSEFN",
  "OING",
  "SOGN",
  "OCDG",
  "OBXU",
  "ATEA",
  "TRMED",
  "SIOFF",
  "INSTA",
  "BORR",
  "INDCT",
  "PARB",
  "NUMND",
  "LYTIX",
  "EPR",
  "HEX",
  "OSEBN",
  "OEXOG",
  "ALT",
  "MOWI",
  "KING",
  "OEXOP",
  "BELCO",
  "OSEBG",
  "WWIB",
  "XXL",
  "KRAB",
  "HUDL",
  "AZT",
  "HYON",
  "GSF",
  "OTELP",
  "STB",
  "CLCO",
  "TGS",
  "OSEBX",
  "BOUV",
  "SSENX",
  "STRO",
  "AUTO",
  "ELO",
  "CONTX",
  "OENP",
  "OTELN",
  "GRONG",
  "OENG",
  "HPUR",
  "QUEST",
  "OTELG",
  "MAS",
  "ELIMP",
  "IWS",
  "OSESX",
  "WPU",
  "REFL",
  "KOA",
  "SSSHP",
  "OBSRV",
  "MEDI",
  "RECSI",
  "ZWIPE",
  "NONG",
  "OUTN",
  "EQNR",
  "PEN",
  "DNO",
  "EWIND",
  "OINP",
  "OBMP",
  "HAFNI",
  "CRAYN",
  "OSESN",
  "QFUEL",
  "RCR",
  "IDEX",
  "NTI",
  "VVL",
  "KIT",
  "SDNS",
  "MING",
  "PPG",
  "OBSHN",
  "NEXT",
  "NEL",
  "NAVA",
  "CAMBI",
  "DVD",
  "HKY",
  "NOM",
  "SEAPT",
  "LUMI",
  "CRNA",
  "PSE",
  "AWDR",
  "KAHOT",
  "NORTH",
  "AFG",
  "OINN",
  "SDRL",
  "RIVER",
  "OHCN",
  "TECH",
  "ELMRA",
  "OBOSX",
  "NODL",
  "OTEC",
  "PLT",
  "OCSG",
  "BCS",
  "SADG",
  "ZENA",
  "VISTN",
  "BWEK",
  "ABS",
  "MELG",
  "GJF",
  "BNOR",
  "BEWI",
  "EIOF",
  "SSENP",
  "PGS",
  "OSESP",
  "MVW",
  "OMDA",
  "OBMG",
  "ENVIP",
  "QEC",
  "NAS",
  "SPOL",
  "AKAST",
  "UNIV",
  "ITERA",
  "OTOVO",
  "CODE",
  "SALME",
  "XPLRA",
  "BRG",
  "INIFY",
  "OREP",
  "VOLUE",
  "WEST",
  "NISB",
  "AKSO",
  "ADS",
  "MGN",
  "AKBM",
  "SKUE",
  "SIKRI",
  "OHCG",
  "VOW",
  "OEXON",
  "OHCP",
  "OBSFX",
  "KCC",
  "NOL",
  "OBXP",
  "SDSD",
  "ARCH",
  "ABG",
  "SSSFP",
  "LIFE",
  "AASB",
  "TEKNA",
  "OTECN",
  "SSSHX",
  "SUBC",
  "TOM",
  "AFISH",
  "VGM",
  "BWLPG",
  "LOKO",
  "CADLR",
  "PROXI",
  "LSG",
  "CARA",
  "OSEMX",
  "BMK",
  "TEL",
  "STST",
  "HDLY",
  "ZAL",
  "PRYME",
  "WAWI",
  "BBERG",
  "OFINP",
  "GIG",
  "BARRA",
  "BIEN",
  "GOGL",
  "VEI",
  "OCSP",
  "OFINN",
  "PROT",
  "EAM",
  "ELK",
  "NORSE",
  "OSEAX",
  "OSEEP",
  "GEM",
  "SOFTX",
  "OAAXP",
  "ENERG",
  "SCATC",
  "DSRT",
  "ROM",
  "AGAS",
  "BFISH",
  "MOBA",
  "HRGI",
  "TRE",
  "ODFB",
  "QFR",
  "KOMPL",
  "OBSFN",
  "ARR",
  "ABTEC",
  "DNB",
  "PNOR",
  "NCOD",
  "NOAP",
  "OTL",
  "ODF",
  "JIN",
  "NORBT",
  "OFING",
  "OBXEN",
  "AKRBP",
  "OSEMP",
  "HUNT",
  "EMGS",
  "OCSN",
  "OSEPX",
  "CAPSL",
  "GCC",
  "TECO",
  "OAAX",
  "AQUIL",
  "OSEBP",
  "ORK",
  "NRC",
  "OENN",
  "OCDP",
  "MPCC",
  "GYL",
  "NOHAL",
  "EFUEL",
  "SCANA",
  "OSEPB",
  "SOON",
  "HBC",
  "HAVI",
  "ININ",
  "DOFG",
  "AKER",
  "5PG",
  "ZAP",
  "PCIB",
];
export const NORWAY_FEED = [
  {
    fullName: null,
    feed: 18177,
    ticker: "2020",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 18177,
    ticker: "OSEXP",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 18177,
    ticker: "AEGA",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 18177,
    ticker: "NTG",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 18177,
    ticker: "ABL",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 18177,
    ticker: "SATS",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 18177,
    ticker: "PHLY",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 18177,
    ticker: "JAREN",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 18177,
    ticker: "KMCP",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 18177,
    ticker: "SASNO",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 18177,
    ticker: "BGBIO",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 18177,
    ticker: "ENSU",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 18177,
    ticker: "RANA",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 18177,
    ticker: "SSG",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 18177,
    ticker: "NHY",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 18177,
    ticker: "OCEAN",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 18177,
    ticker: "AKVA",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 18177,
    ticker: "OCDN",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 18177,
    ticker: "OBSHX",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 18177,
    ticker: "OBX",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 18177,
    ticker: "OSEMN",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 18177,
    ticker: "HELG",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 18177,
    ticker: "IOX",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 18177,
    ticker: "LEA",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 18177,
    ticker: "OBXUP",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 18177,
    ticker: "BALT",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 18177,
    ticker: "CSS",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 18177,
    ticker: "SKAND",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 18177,
    ticker: "CIRCA",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 18177,
    ticker: "SCHB",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 18177,
    ticker: "SBO",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 18177,
    ticker: "NOD",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 18177,
    ticker: "AKOBO",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 18177,
    ticker: "ECIT",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 18177,
    ticker: "BOR",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 18177,
    ticker: "ARGEO",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 18177,
    ticker: "OTECG",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 18177,
    ticker: "OBSHP",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 18177,
    ticker: "HAUTO",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 18177,
    ticker: "B2I",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 18177,
    ticker: "CLOUD",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 18177,
    ticker: "BGBIS",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 18177,
    ticker: "GOD",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 18177,
    ticker: "SB68",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 18177,
    ticker: "ROMSB",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 18177,
    ticker: "BWIDL",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 18177,
    ticker: "OSEAP",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 18177,
    ticker: "SNOR",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 18177,
    ticker: "SUNSB",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 18177,
    ticker: "YAR",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 18177,
    ticker: "REACH",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 18177,
    ticker: "AUSS",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 18177,
    ticker: "KYOTO",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 18177,
    ticker: "TYSB",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 18177,
    ticker: "ENDUR",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 18177,
    ticker: "OSEFP",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 18177,
    ticker: "OAAXN",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 18177,
    ticker: "ELABS",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 18177,
    ticker: "AFK",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 18177,
    ticker: "OBXEP",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 18177,
    ticker: "KOG",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 18177,
    ticker: "EXTX",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 18177,
    ticker: "OBXD",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 18177,
    ticker: "BWO",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 18177,
    ticker: "BONHR",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 18177,
    ticker: "LINK",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 18177,
    ticker: "ASTK",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 18177,
    ticker: "ASA",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 18177,
    ticker: "SAGA",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 18177,
    ticker: "OTECP",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 18177,
    ticker: "IFISH",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 18177,
    ticker: "OREG",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 18177,
    ticker: "SOAG",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 18177,
    ticker: "WWI",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 18177,
    ticker: "MPCES",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 18177,
    ticker: "MORG",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 18177,
    ticker: "VAR",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 18177,
    ticker: "SACAM",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 18177,
    ticker: "ODL",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 18177,
    ticker: "SVEG",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 18177,
    ticker: "OSEER",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 18177,
    ticker: "NKR",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 18177,
    ticker: "OTS",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 18177,
    ticker: "POL",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 18177,
    ticker: "AYFIE",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 18177,
    ticker: "SNI",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 18177,
    ticker: "NAPA",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 18177,
    ticker: "PHO",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 18177,
    ticker: "SHLF",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 18177,
    ticker: "DDRIL",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 18177,
    ticker: "SBX",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 18177,
    ticker: "NSOL",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 18177,
    ticker: "HYN",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 18177,
    ticker: "SOR",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 18177,
    ticker: "NORDH",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 18177,
    ticker: "STSU",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 18177,
    ticker: "RING",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 18177,
    ticker: "OUTG",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 18177,
    ticker: "AURA",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 18177,
    ticker: "TOTG",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 18177,
    ticker: "SPOG",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 18177,
    ticker: "RISH",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 18177,
    ticker: "AMSC",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 18177,
    ticker: "MULTI",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 18177,
    ticker: "OKEA",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 18177,
    ticker: "OBOSP",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 18177,
    ticker: "AGLX",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 18177,
    ticker: "BWE",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 18177,
    ticker: "OSEAN",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 18177,
    ticker: "OBSFP",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 18177,
    ticker: "OREN",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 18177,
    ticker: "BAKKA",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 18177,
    ticker: "OSEEX",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 18177,
    ticker: "PRS",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 18177,
    ticker: "ACC",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 18177,
    ticker: "ENTRA",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 18177,
    ticker: "EQVA",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 18177,
    ticker: "PYRUM",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 18177,
    ticker: "HSHP",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 18177,
    ticker: "OSEFX",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 18177,
    ticker: "STATT",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 18177,
    ticker: "WSTEP",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 18177,
    ticker: "OBMN",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 18177,
    ticker: "ROMER",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 18177,
    ticker: "GENT",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 18177,
    ticker: "ISLAX",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 18177,
    ticker: "SOFF",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 18177,
    ticker: "MVE",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 18177,
    ticker: "SMCRT",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 18177,
    ticker: "ANDF",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 18177,
    ticker: "ACR",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 18177,
    ticker: "ALNG",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 18177,
    ticker: "OSUN",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 18177,
    ticker: "FRO",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 18177,
    ticker: "NORAM",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 18177,
    ticker: "AIRX",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 18177,
    ticker: "AURG",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 18177,
    ticker: "OUTP",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 18177,
    ticker: "TIETO",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 18177,
    ticker: "SCHA",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 18177,
    ticker: "GIGA",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 18177,
    ticker: "SPOT",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 18177,
    ticker: "KID",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 18177,
    ticker: "ADE",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 18177,
    ticker: "HYPRO",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 18177,
    ticker: "PEXIP",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 18177,
    ticker: "OSEBS",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 18177,
    ticker: "NSKOG",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 18177,
    ticker: "SRBNK",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 18177,
    ticker: "SSSFX",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 18177,
    ticker: "ASTRO",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 18177,
    ticker: "MNTR",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 18177,
    ticker: "OET",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 18177,
    ticker: "HAV",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 18177,
    ticker: "NBX",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 18177,
    ticker: "BSP",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 18177,
    ticker: "OLT",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 18177,
    ticker: "SMOP",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 18177,
    ticker: "AKH",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 18177,
    ticker: "ULTI",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 18177,
    ticker: "BMA",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 18177,
    ticker: "GEOS",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 18177,
    ticker: "SALM",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 18177,
    ticker: "HSPG",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 18177,
    ticker: "FLNG",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 18177,
    ticker: "CYVIZ",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 18177,
    ticker: "NYKD",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 18177,
    ticker: "OBXES",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 18177,
    ticker: "OSEFN",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 18177,
    ticker: "OING",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 18177,
    ticker: "SOGN",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 18177,
    ticker: "OCDG",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 18177,
    ticker: "OBXU",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 18177,
    ticker: "ATEA",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 18177,
    ticker: "TRMED",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 18177,
    ticker: "SIOFF",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 18177,
    ticker: "INSTA",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 18177,
    ticker: "BORR",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 18177,
    ticker: "INDCT",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 18177,
    ticker: "PARB",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 18177,
    ticker: "NUMND",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 18177,
    ticker: "LYTIX",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 18177,
    ticker: "EPR",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 18177,
    ticker: "HEX",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 18177,
    ticker: "OSEBN",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 18177,
    ticker: "OEXOG",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 18177,
    ticker: "ALT",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 18177,
    ticker: "MOWI",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 18177,
    ticker: "KING",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 18177,
    ticker: "OEXOP",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 18177,
    ticker: "BELCO",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 18177,
    ticker: "OSEBG",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 18177,
    ticker: "WWIB",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 18177,
    ticker: "XXL",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 18177,
    ticker: "KRAB",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 18177,
    ticker: "HUDL",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 18177,
    ticker: "AZT",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 18177,
    ticker: "HYON",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 18177,
    ticker: "GSF",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 18177,
    ticker: "OTELP",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 18177,
    ticker: "STB",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 18177,
    ticker: "CLCO",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 18177,
    ticker: "TGS",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 18177,
    ticker: "OSEBX",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 18177,
    ticker: "BOUV",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 18177,
    ticker: "SSENX",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 18177,
    ticker: "STRO",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 18177,
    ticker: "AUTO",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 18177,
    ticker: "ELO",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 18177,
    ticker: "CONTX",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 18177,
    ticker: "OENP",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 18177,
    ticker: "OTELN",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 18177,
    ticker: "GRONG",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 18177,
    ticker: "OENG",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 18177,
    ticker: "HPUR",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 18177,
    ticker: "QUEST",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 18177,
    ticker: "OTELG",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 18177,
    ticker: "MAS",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 18177,
    ticker: "ELIMP",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 18177,
    ticker: "IWS",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 18177,
    ticker: "OSESX",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 18177,
    ticker: "WPU",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 18177,
    ticker: "REFL",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 18177,
    ticker: "KOA",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 18177,
    ticker: "SSSHP",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 18177,
    ticker: "OBSRV",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 18177,
    ticker: "MEDI",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 18177,
    ticker: "RECSI",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 18177,
    ticker: "ZWIPE",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 18177,
    ticker: "NONG",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 18177,
    ticker: "OUTN",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 18177,
    ticker: "EQNR",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 18177,
    ticker: "PEN",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 18177,
    ticker: "DNO",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 18177,
    ticker: "EWIND",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 18177,
    ticker: "OINP",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 18177,
    ticker: "OBMP",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 18177,
    ticker: "HAFNI",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 18177,
    ticker: "CRAYN",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 18177,
    ticker: "OSESN",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 18177,
    ticker: "QFUEL",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 18177,
    ticker: "RCR",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 18177,
    ticker: "IDEX",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 18177,
    ticker: "NTI",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 18177,
    ticker: "VVL",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 18177,
    ticker: "KIT",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 18177,
    ticker: "SDNS",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 18177,
    ticker: "MING",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 18177,
    ticker: "PPG",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 18177,
    ticker: "OBSHN",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 18177,
    ticker: "NEXT",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 18177,
    ticker: "NEL",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 18177,
    ticker: "NAVA",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 18177,
    ticker: "CAMBI",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 18177,
    ticker: "DVD",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 18177,
    ticker: "HKY",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 18177,
    ticker: "NOM",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 18177,
    ticker: "SEAPT",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 18177,
    ticker: "LUMI",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 18177,
    ticker: "CRNA",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 18177,
    ticker: "PSE",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 18177,
    ticker: "AWDR",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 18177,
    ticker: "KAHOT",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 18177,
    ticker: "NORTH",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 18177,
    ticker: "AFG",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 18177,
    ticker: "OINN",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 18177,
    ticker: "SDRL",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 18177,
    ticker: "RIVER",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 18177,
    ticker: "OHCN",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 18177,
    ticker: "TECH",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 18177,
    ticker: "ELMRA",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 18177,
    ticker: "OBOSX",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 18177,
    ticker: "NODL",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 18177,
    ticker: "OTEC",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 18177,
    ticker: "PLT",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 18177,
    ticker: "OCSG",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 18177,
    ticker: "BCS",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 18177,
    ticker: "SADG",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 18177,
    ticker: "ZENA",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 18177,
    ticker: "VISTN",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 18177,
    ticker: "BWEK",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 18177,
    ticker: "ABS",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 18177,
    ticker: "MELG",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 18177,
    ticker: "GJF",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 18177,
    ticker: "BNOR",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 18177,
    ticker: "BEWI",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 18177,
    ticker: "EIOF",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 18177,
    ticker: "SSENP",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 18177,
    ticker: "PGS",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 18177,
    ticker: "OSESP",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 18177,
    ticker: "MVW",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 18177,
    ticker: "OMDA",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 18177,
    ticker: "OBMG",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 18177,
    ticker: "ENVIP",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 18177,
    ticker: "QEC",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 18177,
    ticker: "NAS",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 18177,
    ticker: "SPOL",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 18177,
    ticker: "AKAST",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 18177,
    ticker: "UNIV",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 18177,
    ticker: "ITERA",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 18177,
    ticker: "OTOVO",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 18177,
    ticker: "CODE",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 18177,
    ticker: "SALME",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 18177,
    ticker: "XPLRA",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 18177,
    ticker: "BRG",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 18177,
    ticker: "INIFY",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 18177,
    ticker: "OREP",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 18177,
    ticker: "VOLUE",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 18177,
    ticker: "WEST",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 18177,
    ticker: "NISB",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 18177,
    ticker: "AKSO",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 18177,
    ticker: "ADS",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 18177,
    ticker: "MGN",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 18177,
    ticker: "AKBM",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 18177,
    ticker: "SKUE",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 18177,
    ticker: "SIKRI",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 18177,
    ticker: "OHCG",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 18177,
    ticker: "VOW",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 18177,
    ticker: "OEXON",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 18177,
    ticker: "OHCP",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 18177,
    ticker: "OBSFX",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 18177,
    ticker: "KCC",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 18177,
    ticker: "NOL",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 18177,
    ticker: "OBXP",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 18177,
    ticker: "SDSD",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 18177,
    ticker: "ARCH",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 18177,
    ticker: "ABG",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 18177,
    ticker: "SSSFP",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 18177,
    ticker: "LIFE",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 18177,
    ticker: "AASB",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 18177,
    ticker: "TEKNA",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 18177,
    ticker: "OTECN",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 18177,
    ticker: "SSSHX",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 18177,
    ticker: "SUBC",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 18177,
    ticker: "TOM",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 18177,
    ticker: "AFISH",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 18177,
    ticker: "VGM",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 18177,
    ticker: "BWLPG",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 18177,
    ticker: "LOKO",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 18177,
    ticker: "CADLR",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 18177,
    ticker: "PROXI",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 18177,
    ticker: "LSG",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 18177,
    ticker: "CARA",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 18177,
    ticker: "OSEMX",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 18177,
    ticker: "BMK",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 18177,
    ticker: "TEL",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 18177,
    ticker: "STST",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 18177,
    ticker: "HDLY",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 18177,
    ticker: "ZAL",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 18177,
    ticker: "PRYME",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 18177,
    ticker: "WAWI",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 18177,
    ticker: "BBERG",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 18177,
    ticker: "OFINP",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 18177,
    ticker: "GIG",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 18177,
    ticker: "BARRA",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 18177,
    ticker: "BIEN",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 18177,
    ticker: "GOGL",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 18177,
    ticker: "VEI",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 18177,
    ticker: "OCSP",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 18177,
    ticker: "OFINN",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 18177,
    ticker: "PROT",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 18177,
    ticker: "EAM",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 18177,
    ticker: "ELK",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 18177,
    ticker: "NORSE",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 18177,
    ticker: "OSEAX",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 18177,
    ticker: "OSEEP",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 18177,
    ticker: "GEM",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 18177,
    ticker: "SOFTX",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 18177,
    ticker: "OAAXP",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 18177,
    ticker: "ENERG",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 18177,
    ticker: "SCATC",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 18177,
    ticker: "DSRT",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 18177,
    ticker: "ROM",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 18177,
    ticker: "AGAS",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 18177,
    ticker: "BFISH",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 18177,
    ticker: "MOBA",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 18177,
    ticker: "HRGI",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 18177,
    ticker: "TRE",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 18177,
    ticker: "ODFB",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 18177,
    ticker: "QFR",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 18177,
    ticker: "KOMPL",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 18177,
    ticker: "OBSFN",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 18177,
    ticker: "ARR",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 18177,
    ticker: "ABTEC",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 18177,
    ticker: "DNB",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 18177,
    ticker: "PNOR",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 18177,
    ticker: "NCOD",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 18177,
    ticker: "NOAP",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 18177,
    ticker: "OTL",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 18177,
    ticker: "ODF",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 18177,
    ticker: "JIN",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 18177,
    ticker: "NORBT",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 18177,
    ticker: "OFING",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 18177,
    ticker: "OBXEN",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 18177,
    ticker: "AKRBP",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 18177,
    ticker: "OSEMP",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 18177,
    ticker: "HUNT",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 18177,
    ticker: "EMGS",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 18177,
    ticker: "OCSN",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 18177,
    ticker: "OSEPX",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 18177,
    ticker: "CAPSL",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 18177,
    ticker: "GCC",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 18177,
    ticker: "TECO",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 18177,
    ticker: "OAAX",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 18177,
    ticker: "AQUIL",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 18177,
    ticker: "OSEBP",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 18177,
    ticker: "ORK",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 18177,
    ticker: "NRC",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 18177,
    ticker: "OENN",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 18177,
    ticker: "OCDP",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 18177,
    ticker: "MPCC",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 18177,
    ticker: "GYL",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 18177,
    ticker: "NOHAL",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 18177,
    ticker: "EFUEL",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 18177,
    ticker: "SCANA",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 18177,
    ticker: "OSEPB",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 18177,
    ticker: "SOON",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 18177,
    ticker: "HBC",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 18177,
    ticker: "HAVI",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 18177,
    ticker: "ININ",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 18177,
    ticker: "DOFG",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 18177,
    ticker: "AKER",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 18177,
    ticker: "5PG",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 18177,
    ticker: "ZAP",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 18177,
    ticker: "PCIB",
    isin: null,
    mic: null,
    currency: null,
  },
];
