export const CURRENCIES_FEED = [
  {
    fullName: "Norwegian Krona / Polish Zloty",
    feed: 12,
    ticker: "NOKPLN",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: "Mexican Peso / Swedish Krona",
    feed: 12,
    ticker: "MXNSEK",
    isin: null,
    mic: null,
    currency: "SEK",
  },
  {
    fullName: "US Dollar / Thai Bath",
    feed: 12,
    ticker: "USDTHB",
    isin: null,
    mic: null,
    currency: "THB",
  },
  {
    fullName: "US Dollar/South African Rand Cents",
    feed: 12,
    ticker: "USDZAC",
    isin: null,
    mic: null,
    currency: "ZAC",
  },
  {
    fullName: "US Dollar / UAE Dirham",
    feed: 12,
    ticker: "USDAED",
    isin: null,
    mic: null,
    currency: "AED",
  },
  {
    fullName: "Euro / UAE Dirham",
    feed: 12,
    ticker: "EURAED",
    isin: null,
    mic: null,
    currency: "AED",
  },
  {
    fullName: "Thai Bath / Euro",
    feed: 12,
    ticker: "THBEUR",
    isin: null,
    mic: null,
    currency: "EUR",
  },
  {
    fullName: "Euro / Thai Bath",
    feed: 12,
    ticker: "EURTHB",
    isin: null,
    mic: null,
    currency: "THB",
  },
  {
    fullName: "Euro / Bahraini Dirar",
    feed: 12,
    ticker: "EURBHD",
    isin: null,
    mic: null,
    currency: "BHD",
  },
  {
    fullName: "US Dollar / Bahraini Dirar",
    feed: 12,
    ticker: "USDBHD",
    isin: null,
    mic: null,
    currency: "BHD",
  },
  {
    fullName: "Swiss Franc / Nigarian Naira",
    feed: 12,
    ticker: "CHFNGN",
    isin: null,
    mic: null,
    currency: "NGN",
  },
  {
    fullName: "Nigerian Naira / Kenyan Shilling",
    feed: 12,
    ticker: "NGNKES",
    isin: null,
    mic: null,
    currency: "",
  },
  {
    fullName: "US Dollar / Brazilian Real",
    feed: 12,
    ticker: "USDBRL",
    isin: null,
    mic: null,
    currency: "BRL",
  },
  {
    fullName: "US Dollar / Euro",
    feed: 12,
    ticker: "USDEUR",
    isin: null,
    mic: null,
    currency: "EUR",
  },
  {
    fullName: "Swiss Franc / Turkish Lira",
    feed: 12,
    ticker: "CHFTRY",
    isin: null,
    mic: null,
    currency: "TRY",
  },
  {
    fullName: "Euro / US Dollar",
    feed: 12,
    ticker: "EURUSD",
    isin: null,
    mic: null,
    currency: "USD",
  },
  {
    fullName: "Norwegian Krone / Swedish Krona",
    feed: 12,
    ticker: "NOKSEK",
    isin: null,
    mic: null,
    currency: "SEK",
  },
  {
    fullName: "New Zealand Dollar / Japanese Yen",
    feed: 12,
    ticker: "NZDJPY",
    isin: null,
    mic: null,
    currency: "JPY",
  },
  {
    fullName: "US Dollar / Bangladesh Taka",
    feed: 12,
    ticker: "USDBDT",
    isin: null,
    mic: null,
    currency: "BDT",
  },
  {
    fullName: "Czech Koruna / Norwegian Krone",
    feed: 12,
    ticker: "CZKNOK",
    isin: null,
    mic: null,
    currency: "NOK",
  },
  {
    fullName: "Australian Dollar / Canadian Dollar",
    feed: 12,
    ticker: "AUDCAD",
    isin: null,
    mic: null,
    currency: "CAD",
  },
  {
    fullName: "South African Rand / Swiss Franc",
    feed: 12,
    ticker: "ZARCHF",
    isin: null,
    mic: null,
    currency: "CHF",
  },
  {
    fullName: "US Dollar / Norwegian Krone",
    feed: 12,
    ticker: "USDNOK",
    isin: null,
    mic: null,
    currency: "NOK",
  },
  {
    fullName: "Euro / Canadian Dollar",
    feed: 12,
    ticker: "EURCAD",
    isin: null,
    mic: null,
    currency: "CAD",
  },
  {
    fullName: "US Dollar / Canadian Dollar",
    feed: 12,
    ticker: "USDCAD",
    isin: null,
    mic: null,
    currency: "CAD",
  },
  {
    fullName: "Euro / Australian Dollar",
    feed: 12,
    ticker: "EURAUD",
    isin: null,
    mic: null,
    currency: "AUD",
  },
  {
    fullName: "US Dollar / Australian Dollar",
    feed: 12,
    ticker: "USDAUD",
    isin: null,
    mic: null,
    currency: "AUD",
  },
  {
    fullName: "US Dollar / Israel Shekel",
    feed: 12,
    ticker: "USDILS",
    isin: null,
    mic: null,
    currency: "ILS",
  },
  {
    fullName: "US Dollar / Croatian Kuna",
    feed: 12,
    ticker: "USDHRK",
    isin: null,
    mic: null,
    currency: "HRK",
  },
  {
    fullName: "Euro/Japanese Yen",
    feed: 12,
    ticker: "EURJPY",
    isin: null,
    mic: null,
    currency: "JPY",
  },
  {
    fullName: "US Dollar / Japanese Yen",
    feed: 12,
    ticker: "USDJPY",
    isin: null,
    mic: null,
    currency: "JPY",
  },
  {
    fullName: "US Dollar / Danish Krone",
    feed: 12,
    ticker: "USDDKK",
    isin: null,
    mic: null,
    currency: "DKK",
  },
  {
    fullName: "Euro / Danish Krone",
    feed: 12,
    ticker: "EURDKK",
    isin: null,
    mic: null,
    currency: "DKK",
  },
  {
    fullName: "Japanese Yen / Danish Krone",
    feed: 12,
    ticker: "JPYDKK",
    isin: null,
    mic: null,
    currency: "DKK",
  },
  {
    fullName: "US Dollar / Turkish Lira",
    feed: 12,
    ticker: "USDTRY",
    isin: null,
    mic: null,
    currency: "TRY",
  },
  {
    fullName: "British Pound / Canadian Dollar",
    feed: 12,
    ticker: "GBPCAD",
    isin: null,
    mic: null,
    currency: "CAD",
  },
  {
    fullName: "Australian Dollar / Hong Kong Dollar",
    feed: 12,
    ticker: "AUDHKD",
    isin: null,
    mic: null,
    currency: "HKD",
  },
  {
    fullName: "Euro / Turkish Lira",
    feed: 12,
    ticker: "EURTRY",
    isin: null,
    mic: null,
    currency: "TRY",
  },
  {
    fullName: "Euro / South African Rand",
    feed: 12,
    ticker: "EURZAR",
    isin: null,
    mic: null,
    currency: "ZAR",
  },
  {
    fullName: "New Zealand Dollar / Danish Kroner",
    feed: 12,
    ticker: "NZDDKK",
    isin: null,
    mic: null,
    currency: "DKK",
  },
  {
    fullName: "Australian Dollar / US Dollar",
    feed: 12,
    ticker: "AUDUSD",
    isin: null,
    mic: null,
    currency: "USD",
  },
  {
    fullName: "Euro / Singapore Dollar",
    feed: 12,
    ticker: "EURSGD",
    isin: null,
    mic: null,
    currency: "SGD",
  },
  {
    fullName: "British Pound / Euro",
    feed: 12,
    ticker: "GBPEUR",
    isin: null,
    mic: null,
    currency: "EUR",
  },
  {
    fullName: "US Dollar / Chilean Peso",
    feed: 12,
    ticker: "USDCLP",
    isin: null,
    mic: null,
    currency: "CLP",
  },
  {
    fullName: "US Dollar / Czech Koruna",
    feed: 12,
    ticker: "USDCZK",
    isin: null,
    mic: null,
    currency: "CZK",
  },
  {
    fullName: "Euro / Czech Koruna",
    feed: 12,
    ticker: "EURCZK",
    isin: null,
    mic: null,
    currency: "CZK",
  },
  {
    fullName: "Australian Dollar / New Zealand Dollar",
    feed: 12,
    ticker: "AUDNZD",
    isin: null,
    mic: null,
    currency: "NZD",
  },
  {
    fullName: "British Pound / US Dollar",
    feed: 12,
    ticker: "GBPUSD",
    isin: null,
    mic: null,
    currency: "USD",
  },
  {
    fullName: "British Pound / Polish Zloty",
    feed: 12,
    ticker: "GBPPLN",
    isin: null,
    mic: null,
    currency: "PLN",
  },
  {
    fullName: "Australian Dollar / South African Rand",
    feed: 12,
    ticker: "AUDZAR",
    isin: null,
    mic: null,
    currency: "ZAR",
  },
  {
    fullName: "Swiss Franc / Australian Dollar",
    feed: 12,
    ticker: "CHFAUD",
    isin: null,
    mic: null,
    currency: "AUD",
  },
  {
    fullName: "US Dollar / Swiss Franc",
    feed: 12,
    ticker: "USDCHF",
    isin: null,
    mic: null,
    currency: "CHF",
  },
  {
    fullName: "British Pound / Danish Krone",
    feed: 12,
    ticker: "GBPDKK",
    isin: null,
    mic: null,
    currency: "DKK",
  },
  {
    fullName: "Euro / Swiss Franc",
    feed: 12,
    ticker: "EURCHF",
    isin: null,
    mic: null,
    currency: "CHF",
  },
  {
    fullName: "British Pence / South African Rand",
    feed: 12,
    ticker: "GBXZAC",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: "British Pound / Australian Dollar",
    feed: 12,
    ticker: "GBPAUD",
    isin: null,
    mic: null,
    currency: "AUD",
  },
  {
    fullName: "Swiss Franc / Danish Kroner",
    feed: 12,
    ticker: "CHFDKK",
    isin: null,
    mic: null,
    currency: "DKK",
  },
  {
    fullName: "Euro / Hong Kong Dollar",
    feed: 12,
    ticker: "EURHKD",
    isin: null,
    mic: null,
    currency: "HKD",
  },
  {
    fullName: "US Dollar / Pakistanian Rupee",
    feed: 12,
    ticker: "USDPKR",
    isin: null,
    mic: null,
    currency: "PKR",
  },
  {
    fullName: "Icelandic Krone / Danish Krone",
    feed: 12,
    ticker: "ISKDKK",
    isin: null,
    mic: null,
    currency: "DKK",
  },
  {
    fullName: "New Zealand Dollar / Norwegian Krone",
    feed: 12,
    ticker: "NZDNOK",
    isin: null,
    mic: null,
    currency: "NOK",
  },
  {
    fullName: "Mexican Peso / Swiss Franc",
    feed: 12,
    ticker: "MXNCHF",
    isin: null,
    mic: null,
    currency: "CHF",
  },
  {
    fullName: "Kenyan Shilling / Nigerian Naira",
    feed: 12,
    ticker: "KESNGN",
    isin: null,
    mic: null,
    currency: "",
  },
  {
    fullName: "New Zealand Dollar / US Dollar",
    feed: 12,
    ticker: "NZDUSD",
    isin: null,
    mic: null,
    currency: "USD",
  },
  {
    fullName: "US Dollar / Moroccan Dirham",
    feed: 12,
    ticker: "USDMAD",
    isin: null,
    mic: null,
    currency: "MAD",
  },
  {
    fullName: "US Dollar/Colombian Peso",
    feed: 12,
    ticker: "USDCOP",
    isin: null,
    mic: null,
    currency: "COP",
  },
  {
    fullName: "Swiss Franc / Japanese Yen",
    feed: 12,
    ticker: "CHFJPY",
    isin: null,
    mic: null,
    currency: "JPY",
  },
  {
    fullName: "Norwegian Krone / South African Rand",
    feed: 12,
    ticker: "NOKZAR",
    isin: null,
    mic: null,
    currency: "ZAR",
  },
  {
    fullName: "US Dollar / Mexican Peso",
    feed: 12,
    ticker: "USDMXN",
    isin: null,
    mic: null,
    currency: "MXN",
  },
  {
    fullName: "US Dollar / New Zealand Dollar",
    feed: 12,
    ticker: "USDNZD",
    isin: null,
    mic: null,
    currency: "NZD",
  },
  {
    fullName: "US Dollar / Polish Zloty",
    feed: 12,
    ticker: "USDPLN",
    isin: null,
    mic: null,
    currency: "PLN",
  },
  {
    fullName: "Australian Dollar / Swedish Krona",
    feed: 12,
    ticker: "AUDSEK",
    isin: null,
    mic: null,
    currency: "SEK",
  },
  {
    fullName: "Japanese Yen / Norwegian Krone",
    feed: 12,
    ticker: "JPYNOK",
    isin: null,
    mic: null,
    currency: "NOK",
  },
  {
    fullName: "Swiss Fran / Polish Zloty",
    feed: 12,
    ticker: "CHFPLN",
    isin: null,
    mic: null,
    currency: "PLN",
  },
  {
    fullName: "Canadian Dollar / Norwegian Krone",
    feed: 12,
    ticker: "CADNOK",
    isin: null,
    mic: null,
    currency: "NOK",
  },
  {
    fullName: "US Dollar / Russian Ruble",
    feed: 12,
    ticker: "USDRUB",
    isin: null,
    mic: null,
    currency: "RUB",
  },
  {
    fullName: "Danish Krone / Norwegian Krone",
    feed: 12,
    ticker: "DKKNOK",
    isin: null,
    mic: null,
    currency: "NOK",
  },
  {
    fullName: "US Dollar / Indian Rupee",
    feed: 12,
    ticker: "USDINR",
    isin: null,
    mic: null,
    currency: "INR",
  },
  {
    fullName: "Kenyan Shilling / US Dollar",
    feed: 12,
    ticker: "KESUSD",
    isin: null,
    mic: null,
    currency: "USD",
  },
  {
    fullName: "British Pound / Singapore Dollar",
    feed: 12,
    ticker: "GBPSGD",
    isin: null,
    mic: null,
    currency: "SGD",
  },
  {
    fullName: "US Dollar / Swedish Krona",
    feed: 12,
    ticker: "USDSEK",
    isin: null,
    mic: null,
    currency: "SEK",
  },
  {
    fullName: "Croatian Kuna / Norwegian Krone",
    feed: 12,
    ticker: "HRKNOK",
    isin: null,
    mic: null,
    currency: "NOK",
  },
  {
    fullName: "US Dollar / Vietnam Dong",
    feed: 12,
    ticker: "USDVND",
    isin: null,
    mic: null,
    currency: "VND",
  },
  {
    fullName: "Japanese Yen / Swedish Krona",
    feed: 12,
    ticker: "JPYSEK",
    isin: null,
    mic: null,
    currency: "SEK",
  },
  {
    fullName: "Swedish Krona / Norwegian Krone",
    feed: 12,
    ticker: "SEKNOK",
    isin: null,
    mic: null,
    currency: "NOK",
  },
  {
    fullName: "US Dollar / Ukranian Hryvnia",
    feed: 12,
    ticker: "USDUAH",
    isin: null,
    mic: null,
    currency: "UAH",
  },
  {
    fullName: "US Dollar / Phillipine Peso",
    feed: 12,
    ticker: "USDPHP",
    isin: null,
    mic: null,
    currency: "PHP",
  },
  {
    fullName: "Canadian Dollar / Japanese Yen",
    feed: 12,
    ticker: "CADJPY",
    isin: null,
    mic: null,
    currency: "JPY",
  },
  {
    fullName: "Euro / Chinese Yuan Renminbi",
    feed: 12,
    ticker: "EURCNY",
    isin: null,
    mic: null,
    currency: "CNY",
  },
  {
    fullName: "Malaysian Ringgit / Swedish Krona",
    feed: 12,
    ticker: "MYRSEK",
    isin: null,
    mic: null,
    currency: "SEK",
  },
  {
    fullName: "Nigarian Naira / US Dollar",
    feed: 12,
    ticker: "NGNUSD",
    isin: null,
    mic: null,
    currency: "USD",
  },
  {
    fullName: "US Dollar / Indonasian Rupiah",
    feed: 12,
    ticker: "USDIDR",
    isin: null,
    mic: null,
    currency: "IDR",
  },
  {
    fullName: "Euro / Malaysian Ringgit",
    feed: 12,
    ticker: "EURMYR",
    isin: null,
    mic: null,
    currency: "MYR",
  },
  {
    fullName: "Swiss Franc / Kenyan Shilling",
    feed: 12,
    ticker: "CHFKES",
    isin: null,
    mic: null,
    currency: "KES",
  },
  {
    fullName: "British Pound / New Zealand Dollar",
    feed: 12,
    ticker: "GBPNZD",
    isin: null,
    mic: null,
    currency: "NZD",
  },
  {
    fullName: "Swiss Franc / Brasilian Real",
    feed: 12,
    ticker: "CHFBRL",
    isin: null,
    mic: null,
    currency: "BRL",
  },
  {
    fullName: "US Dollar / Hong Kong Dollar",
    feed: 12,
    ticker: "USDHKD",
    isin: null,
    mic: null,
    currency: "HKD",
  },
  {
    fullName: "Australian Dollar / Kenyan Shilling",
    feed: 12,
    ticker: "AUDKES",
    isin: null,
    mic: null,
    currency: "KES",
  },
  {
    fullName: "Euro / Islandic Krone",
    feed: 12,
    ticker: "EURISK",
    isin: null,
    mic: null,
    currency: "ISK",
  },
  {
    fullName: "Euro / New Zealand Dollar",
    feed: 12,
    ticker: "EURNZD",
    isin: null,
    mic: null,
    currency: "NZD",
  },
  {
    fullName: "Canadian Dollar / Swedish Krona",
    feed: 12,
    ticker: "CADSEK",
    isin: null,
    mic: null,
    currency: "SEK",
  },
  {
    fullName: "British Pence / New Zealand Dollar",
    feed: 12,
    ticker: "GBXNZD",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: "US Dollar / Saudi Arabian Riyal",
    feed: 12,
    ticker: "USDSAR",
    isin: null,
    mic: null,
    currency: "SAR",
  },
  {
    fullName: "Czech Koruna / Brasilian Real",
    feed: 12,
    ticker: "CZKBRL",
    isin: null,
    mic: null,
    currency: "BRL",
  },
  {
    fullName: "Australian Dollar / Japanese Yen",
    feed: 12,
    ticker: "AUDJPY",
    isin: null,
    mic: null,
    currency: "JPY",
  },
  {
    fullName: "Czech Koruna / Turkism Lira",
    feed: 12,
    ticker: "CZKTRY",
    isin: null,
    mic: null,
    currency: "TRY",
  },
  {
    fullName: "US Dollar / Egyptian Pound",
    feed: 12,
    ticker: "USDEGP",
    isin: null,
    mic: null,
    currency: "EGP",
  },
  {
    fullName: "British Pence / Kenyan Shilling",
    feed: 12,
    ticker: "GBXKES",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: "British Pound / Swiss Franc",
    feed: 12,
    ticker: "GBPCHF",
    isin: null,
    mic: null,
    currency: "CHF",
  },
  {
    fullName: "US Dollar / Islandic Krone",
    feed: 12,
    ticker: "USDISK",
    isin: null,
    mic: null,
    currency: "ISK",
  },
  {
    fullName: "US Dollar / Singapore Dollar",
    feed: 12,
    ticker: "USDSGD",
    isin: null,
    mic: null,
    currency: "SGD",
  },
  {
    fullName: "Euro / Swedish Krona",
    feed: 12,
    ticker: "EURSEK",
    isin: null,
    mic: null,
    currency: "SEK",
  },
  {
    fullName: "US Dollar / Hungarian Forint",
    feed: 12,
    ticker: "USDHUF",
    isin: null,
    mic: null,
    currency: "HUF",
  },
  {
    fullName: "US Dollar / Taiwan Dollar",
    feed: 12,
    ticker: "USDTWD",
    isin: null,
    mic: null,
    currency: "TWD",
  },
  {
    fullName: "New Zealand Dollar / Swedish Krona",
    feed: 12,
    ticker: "NZDSEK",
    isin: null,
    mic: null,
    currency: "SEK",
  },
  {
    fullName: "South African Rand / Singapore Dollar",
    feed: 12,
    ticker: "ZARSGD",
    isin: null,
    mic: null,
    currency: "SGD",
  },
  {
    fullName: "US Dollar / Nigarian Naira",
    feed: 12,
    ticker: "USDNGN",
    isin: null,
    mic: null,
    currency: "NGN",
  },
  {
    fullName: "Danish Krone / Swedish Krona",
    feed: 12,
    ticker: "DKKSEK",
    isin: null,
    mic: null,
    currency: "SEK",
  },
  {
    fullName: "Swedish Krona / Euro",
    feed: 12,
    ticker: "SEKEUR",
    isin: null,
    mic: null,
    currency: "EUR",
  },
  {
    fullName: "US Dollar / Qatar Rial",
    feed: 12,
    ticker: "USDQAR",
    isin: null,
    mic: null,
    currency: "QAR",
  },
  {
    fullName: "British Pound / Kenyan Shilling",
    feed: 12,
    ticker: "GBPKES",
    isin: null,
    mic: null,
    currency: "KES",
  },
  {
    fullName: "US Dollar / Chinese Yuan",
    feed: 12,
    ticker: "USDCNY",
    isin: null,
    mic: null,
    currency: "CNY",
  },
  {
    fullName: "Japanese Yen / Nigarian Naira",
    feed: 12,
    ticker: "JPYNGN",
    isin: null,
    mic: null,
    currency: "NGN",
  },
  {
    fullName: "Swiss Franc / Swedish Krona",
    feed: 12,
    ticker: "CHFSEK",
    isin: null,
    mic: null,
    currency: "SEK",
  },
  {
    fullName: "Bulgarian Levs / Swedish Krona",
    feed: 12,
    ticker: "BGNSEK",
    isin: null,
    mic: null,
    currency: "SEK",
  },
  {
    fullName: "British Pound / Islandic Krone",
    feed: 12,
    ticker: "GBPISK",
    isin: null,
    mic: null,
    currency: "ISK",
  },
  {
    fullName: "Czech Koruna / Danish Krone",
    feed: 12,
    ticker: "CZKDKK",
    isin: null,
    mic: null,
    currency: "DKK",
  },
  {
    fullName: "Euro / Mexican Peso",
    feed: 12,
    ticker: "EURMXN",
    isin: null,
    mic: null,
    currency: "MXN",
  },
  {
    fullName: "British Pound / Brazilian Real",
    feed: 12,
    ticker: "GBPBRL",
    isin: null,
    mic: null,
    currency: "BRL",
  },
  {
    fullName: "US Dollar / British Pound",
    feed: 12,
    ticker: "USDGBP",
    isin: null,
    mic: null,
    currency: "GBP",
  },
  {
    fullName: "British Pound / Japanese Yen",
    feed: 12,
    ticker: "GBPJPY",
    isin: null,
    mic: null,
    currency: "JPY",
  },
  {
    fullName: "Vietnam Dong / Euro",
    feed: 12,
    ticker: "VNDEUR",
    isin: null,
    mic: null,
    currency: "EUR",
  },
  {
    fullName: "US Dollar / Malaysian Ringgit",
    feed: 12,
    ticker: "USDMYR",
    isin: null,
    mic: null,
    currency: "MYR",
  },
  {
    fullName: "Singapore Dollar / Danish Krone",
    feed: 12,
    ticker: "SGDDKK",
    isin: null,
    mic: null,
    currency: "DKK",
  },
  {
    fullName: "Singapore Dollar / Swedish Krona",
    feed: 12,
    ticker: "SGDSEK",
    isin: null,
    mic: null,
    currency: "SEK",
  },
  {
    fullName: "Euro / Polish Zloty",
    feed: 12,
    ticker: "EURPLN",
    isin: null,
    mic: null,
    currency: "PLN",
  },
  {
    fullName: "Turkish Lira / South African Rand",
    feed: 12,
    ticker: "TRYZAR",
    isin: null,
    mic: null,
    currency: "ZAR",
  },
  {
    fullName: "Euro/British Pound",
    feed: 12,
    ticker: "EURGBP",
    isin: null,
    mic: null,
    currency: "GBP",
  },
  {
    fullName: "Turkish Lira / Norwegian Krone",
    feed: 12,
    ticker: "TRYNOK",
    isin: null,
    mic: null,
    currency: "NOK",
  },
  {
    fullName: "British Pound / Swedish Krona",
    feed: 12,
    ticker: "GBPSEK",
    isin: null,
    mic: null,
    currency: "SEK",
  },
  {
    fullName: "Australian Dollar / Danish Krone",
    feed: 12,
    ticker: "AUDDKK",
    isin: null,
    mic: null,
    currency: "DKK",
  },
  {
    fullName: "US Dollar / South African Rand",
    feed: 12,
    ticker: "USDZAR",
    isin: null,
    mic: null,
    currency: "ZAR",
  },
  {
    fullName: "Canadian Dollar / Icelandic Krone",
    feed: 12,
    ticker: "CADISK",
    isin: null,
    mic: null,
    currency: "ISK",
  },
  {
    fullName: "Swiss Franc / Norwegian Krone",
    feed: 12,
    ticker: "CHFNOK",
    isin: null,
    mic: null,
    currency: "NOK",
  },
  {
    fullName: "US Dollar / Korean Won",
    feed: 12,
    ticker: "USDKRW",
    isin: null,
    mic: null,
    currency: "KRW",
  },
  {
    fullName: "Norwegian Krone / Danish Krone",
    feed: 12,
    ticker: "NOKDKK",
    isin: null,
    mic: null,
    currency: "DKK",
  },
  {
    fullName: "Euro / Hungarian Forint",
    feed: 12,
    ticker: "EURHUF",
    isin: null,
    mic: null,
    currency: "HUF",
  },
  {
    fullName: "Hong Kong Dollar / Danish Krone",
    feed: 12,
    ticker: "HKDDKK",
    isin: null,
    mic: null,
    currency: "DKK",
  },
  {
    fullName: "Euro / Russian Ruble",
    feed: 12,
    ticker: "EURRUB",
    isin: null,
    mic: null,
    currency: "RUB",
  },
  {
    fullName: "British Pound / Norwegian Krone",
    feed: 12,
    ticker: "GBPNOK",
    isin: null,
    mic: null,
    currency: "NOK",
  },
  {
    fullName: "Euro / Norwegian Krone",
    feed: 12,
    ticker: "EURNOK",
    isin: null,
    mic: null,
    currency: "NOK",
  },
  {
    fullName: "Norwegian Krone / Swiss Franc",
    feed: 12,
    ticker: "NOKCHF",
    isin: null,
    mic: null,
    currency: "CHF",
  },
  {
    fullName: "South African Rand / New Zealand Dollar",
    feed: 12,
    ticker: "ZARNZD",
    isin: null,
    mic: null,
    currency: "NZD",
  },
  {
    fullName: "Icelandic Krone / Swedish Krona",
    feed: 12,
    ticker: "ISKSEK",
    isin: null,
    mic: null,
    currency: "SEK",
  },
  {
    fullName: "Turkish Lira / Czech Kornua",
    feed: 12,
    ticker: "TRYCZK",
    isin: null,
    mic: null,
    currency: "CZK",
  },
  {
    fullName: "Croatian Kuna / Swedish Krona",
    feed: 12,
    ticker: "HRKSEK",
    isin: null,
    mic: null,
    currency: "SEK",
  },
  {
    fullName: "US Dollar / Belarusian Ruble",
    feed: 12,
    ticker: "USDBYN",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: "Japanese Yen/South African Rand Cents",
    feed: 12,
    ticker: "JPYZAC",
    isin: null,
    mic: null,
    currency: "ZAC",
  },
  {
    fullName: "Polish Zloty / Norwegian Krone",
    feed: 12,
    ticker: "PLNNOK",
    isin: null,
    mic: null,
    currency: "NOK",
  },
  {
    fullName: "Swedish Krona / Mexican Peso",
    feed: 12,
    ticker: "SEKMXN",
    isin: null,
    mic: null,
    currency: "",
  },
  {
    fullName: "South African Rand / Austrialian Dollar",
    feed: 12,
    ticker: "ZARAUD",
    isin: null,
    mic: null,
    currency: "AUD",
  },
  {
    fullName: "Chinese Yuan / Icelandic Crown",
    feed: 12,
    ticker: "CNYISK",
    isin: null,
    mic: null,
    currency: "ISK",
  },
  {
    fullName: "Polish Zloty / Swedish Krona",
    feed: 12,
    ticker: "PLNSEK",
    isin: null,
    mic: null,
    currency: "SEK",
  },
  {
    fullName: "Swedish Krona / US Dollar",
    feed: 12,
    ticker: "SEKUSD",
    isin: null,
    mic: null,
    currency: "USD",
  },
  {
    fullName: "South African Rand / Danish Krone",
    feed: 12,
    ticker: "ZARDKK",
    isin: null,
    mic: null,
    currency: "DKK",
  },
  {
    fullName: "New Zealand Dollar / Swiss Franc",
    feed: 12,
    ticker: "NZDCHF",
    isin: null,
    mic: null,
    currency: "CHF",
  },
  {
    fullName: "Czech Koruna / Icelandic Krone",
    feed: 12,
    ticker: "CZKISK",
    isin: null,
    mic: null,
    currency: "ISK",
  },
  {
    fullName: "Swedish Krona / Icelandic Krone",
    feed: 12,
    ticker: "SEKISK",
    isin: null,
    mic: null,
    currency: "ISK",
  },
  {
    fullName: "Russian Ruble / Swedish Krona",
    feed: 12,
    ticker: "RUBSEK",
    isin: null,
    mic: null,
    currency: "SEK",
  },
  {
    fullName: "Hong Kong Dollar / Norwegian Krone",
    feed: 12,
    ticker: "HKDNOK",
    isin: null,
    mic: null,
    currency: "NOK",
  },
  {
    fullName: "Euro/South African Rand Cents",
    feed: 12,
    ticker: "EURZAC",
    isin: null,
    mic: null,
    currency: "ZAC",
  },
  {
    fullName: "Swedish Krona / South African Rand",
    feed: 12,
    ticker: "SEKZAR",
    isin: null,
    mic: null,
    currency: "ZAR",
  },
  {
    fullName: "Nigarian Naira / British Pound",
    feed: 12,
    ticker: "NGNGBP",
    isin: null,
    mic: null,
    currency: "GBP",
  },
  {
    fullName: "Icelandic Krone Index",
    feed: 12,
    ticker: "ISKB",
    isin: null,
    mic: null,
    currency: "",
  },
  {
    fullName: "New Zealand Dollar / South African Rand",
    feed: 12,
    ticker: "NZDZAR",
    isin: null,
    mic: null,
    currency: "ZAR",
  },
  {
    fullName: null,
    feed: 12,
    ticker: "NOKJPY",
    isin: null,
    mic: null,
    currency: "JPY",
  },
  {
    fullName: "Swiss Franc / Czech Koruna",
    feed: 12,
    ticker: "CHFCZK",
    isin: null,
    mic: null,
    currency: "CZK",
  },
  {
    fullName: "Vietnam Dong / British Pound",
    feed: 12,
    ticker: "VNDGBP",
    isin: null,
    mic: null,
    currency: "GBP",
  },
  {
    fullName: "Malaysian Ringgit / Norwegian Krone",
    feed: 12,
    ticker: "MYRNOK",
    isin: null,
    mic: null,
    currency: "NOK",
  },
  {
    fullName: "Euro / Vietnam Dong",
    feed: 12,
    ticker: "EURVND",
    isin: null,
    mic: null,
    currency: "VND",
  },
  {
    fullName: "South African Rand / Norwegian Krone",
    feed: 12,
    ticker: "ZARNOK",
    isin: null,
    mic: null,
    currency: "NOK",
  },
  {
    fullName: "Swiss Franc / Mexican Peso",
    feed: 12,
    ticker: "CHFMXN",
    isin: null,
    mic: null,
    currency: "MXN",
  },
  {
    fullName: "Mexican Peso / Norwegian Krone",
    feed: 12,
    ticker: "MXNNOK",
    isin: null,
    mic: null,
    currency: "NOK",
  },
  {
    fullName: "South African Rand / Canadian Dollar",
    feed: 12,
    ticker: "ZARCAD",
    isin: null,
    mic: null,
    currency: "CAD",
  },
  {
    fullName: "Turkish Lira / Danish Krone",
    feed: 12,
    ticker: "TRYDKK",
    isin: null,
    mic: null,
    currency: "DKK",
  },
  {
    fullName: "Turkish Lira / Japanese Yen",
    feed: 12,
    ticker: "TRYJPY",
    isin: null,
    mic: null,
    currency: "JPY",
  },
  {
    fullName: "Russian Ruble / Norwegian Krone",
    feed: 12,
    ticker: "RUBNOK",
    isin: null,
    mic: null,
    currency: "NOK",
  },
  {
    fullName: "Czech Koruna / Hungarian Forint",
    feed: 12,
    ticker: "CZKHUF",
    isin: null,
    mic: null,
    currency: "HUF",
  },
  {
    fullName: "Euro / Romanian Leu",
    feed: 12,
    ticker: "EURRON",
    isin: null,
    mic: null,
    currency: "RON",
  },
  {
    fullName: "British Pound / South African Rand",
    feed: 12,
    ticker: "GBPZAR",
    isin: null,
    mic: null,
    currency: "ZAR",
  },
  {
    fullName: "Turkish Lira / Swedish Krona",
    feed: 12,
    ticker: "TRYSEK",
    isin: null,
    mic: null,
    currency: "SEK",
  },
  {
    fullName: "Thai Bath / Danish Krone",
    feed: 12,
    ticker: "THBDKK",
    isin: null,
    mic: null,
    currency: "DKK",
  },
  {
    fullName: "Chinese Yuan / Swedish Krona",
    feed: 12,
    ticker: "CNYSEK",
    isin: null,
    mic: null,
    currency: "SEK",
  },
  {
    fullName: "Nigarian Naira / Euro",
    feed: 12,
    ticker: "NGNEUR",
    isin: null,
    mic: null,
    currency: "EUR",
  },
  {
    fullName: "US Dollar / Bulgarian Levs",
    feed: 12,
    ticker: "USDBGN",
    isin: null,
    mic: null,
    currency: "BGN",
  },
  {
    fullName: "US Dollar / Argentine Pesos",
    feed: 12,
    ticker: "USDARS",
    isin: null,
    mic: null,
    currency: "ARS",
  },
  {
    fullName: "Czech Koruna / Polish Zloty",
    feed: 12,
    ticker: "CZKPLN",
    isin: null,
    mic: null,
    currency: "PLN",
  },
  {
    fullName: "British Pound / Czech Koruna",
    feed: 12,
    ticker: "GBPCZK",
    isin: null,
    mic: null,
    currency: "CZK",
  },
  {
    fullName: "Czech Koruna / US Dollar",
    feed: 12,
    ticker: "CZKUSD",
    isin: null,
    mic: null,
    currency: "USD",
  },
  {
    fullName: "Russian Ruble / Icelandic Krone",
    feed: 12,
    ticker: "RUBISK",
    isin: null,
    mic: null,
    currency: "ISK",
  },
  {
    fullName: "Japanese Yen / Islandic Krone",
    feed: 12,
    ticker: "JPYISK",
    isin: null,
    mic: null,
    currency: "ISK",
  },
  {
    fullName: "Thai Bath / Norwegian Krone",
    feed: 12,
    ticker: "THBNOK",
    isin: null,
    mic: null,
    currency: "NOK",
  },
  {
    fullName: "Czech Koruna / Swedish Krona",
    feed: 12,
    ticker: "CZKSEK",
    isin: null,
    mic: null,
    currency: "SEK",
  },
  {
    fullName: "Hong Kong Dollar / Swedish Krona",
    feed: 12,
    ticker: "HKDSEK",
    isin: null,
    mic: null,
    currency: "SEK",
  },
  {
    fullName: "Euro / Croatian Kune",
    feed: 12,
    ticker: "EURHRK",
    isin: null,
    mic: null,
    currency: "HRK",
  },
  {
    fullName: "British Pence / Polish Zloty",
    feed: 12,
    ticker: "GBXPLN",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: "Czech Koruna / EURO",
    feed: 12,
    ticker: "CZKEUR",
    isin: null,
    mic: null,
    currency: "EUR",
  },
  {
    fullName: "Malaysian Ringgit / Danish Krone",
    feed: 12,
    ticker: "MYRDKK",
    isin: null,
    mic: null,
    currency: "DKK",
  },
  {
    fullName: "Kenyan Shilling / South African Rand",
    feed: 12,
    ticker: "KESZAR",
    isin: null,
    mic: null,
    currency: "ZAR",
  },
  {
    fullName: "Euro / Bulgarian Levs",
    feed: 12,
    ticker: "EURBGN",
    isin: null,
    mic: null,
    currency: "BGN",
  },
  {
    fullName: "Euro / Brasilian Real",
    feed: 12,
    ticker: "EURBRL",
    isin: null,
    mic: null,
    currency: "BRL",
  },
  {
    fullName: "Canadian Dollar / Danish Krone",
    feed: 12,
    ticker: "CADDKK",
    isin: null,
    mic: null,
    currency: "DKK",
  },
  {
    fullName: "Hungarian Forint / Danish Krone",
    feed: 12,
    ticker: "HUFDKK",
    isin: null,
    mic: null,
    currency: "DKK",
  },
  {
    fullName: "Euro / Chinese Yuan in Hong Kong Spot",
    feed: 12,
    ticker: "EURCNH",
    isin: null,
    mic: null,
    currency: "CNH",
  },
  {
    fullName: "New Zealand Dollar / Icelandic Krone",
    feed: 12,
    ticker: "NZDISK",
    isin: null,
    mic: null,
    currency: "ISK",
  },
  {
    fullName: "Swedish Krona / Danish Krone",
    feed: 12,
    ticker: "SEKDKK",
    isin: null,
    mic: null,
    currency: "DKK",
  },
  {
    fullName: "Norwegian Krone / Islandic Krone",
    feed: 12,
    ticker: "NOKISK",
    isin: null,
    mic: null,
    currency: "ISK",
  },
  {
    fullName: "British Pound / Vietnam Dong",
    feed: 12,
    ticker: "GBPVND",
    isin: null,
    mic: null,
    currency: "VND",
  },
  {
    fullName: "Australian Dollar /  South African Rand Cents",
    feed: 12,
    ticker: "AUDZAC",
    isin: null,
    mic: null,
    currency: "ZAC",
  },
  {
    fullName: "British Pence / Icelandic Krone",
    feed: 12,
    ticker: "GBXISK",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: "Mexican Peso / Danish Krone",
    feed: 12,
    ticker: "MXNDKK",
    isin: null,
    mic: null,
    currency: "DKK",
  },
  {
    fullName: "Swiss Franc / Islandic Krone",
    feed: 12,
    ticker: "CHFISK",
    isin: null,
    mic: null,
    currency: "ISK",
  },
  {
    fullName: "Australian Dollar / Norwegian Krone",
    feed: 12,
    ticker: "AUDNOK",
    isin: null,
    mic: null,
    currency: "NOK",
  },
  {
    fullName: "Singapore Dollar / Norwegian Krone",
    feed: 12,
    ticker: "SGDNOK",
    isin: null,
    mic: null,
    currency: "NOK",
  },
  {
    fullName: "Hungarian Forint / Icelandic Krone",
    feed: 12,
    ticker: "HUFISK",
    isin: null,
    mic: null,
    currency: "ISK",
  },
  {
    fullName: "British Pound/South African Rand Cents",
    feed: 12,
    ticker: "GBPZAC",
    isin: null,
    mic: null,
    currency: "ZAC",
  },
  {
    fullName: "US Dollar / Romanian Leu",
    feed: 12,
    ticker: "USDRON",
    isin: null,
    mic: null,
    currency: "RON",
  },
  {
    fullName: "Hungarian Forint / Swedish Krona",
    feed: 12,
    ticker: "HUFSEK",
    isin: null,
    mic: null,
    currency: "SEK",
  },
  {
    fullName: "Hungarian Forint / Norwegian Krone",
    feed: 12,
    ticker: "HUFNOK",
    isin: null,
    mic: null,
    currency: "NOK",
  },
  {
    fullName: "Russian Ruble / Danish Krone",
    feed: 12,
    ticker: "RUBDKK",
    isin: null,
    mic: null,
    currency: "DKK",
  },
  {
    fullName: "British Pound / Turkish Lira",
    feed: 12,
    ticker: "GBPTRY",
    isin: null,
    mic: null,
    currency: "TRY",
  },
  {
    fullName: "British Pence / Japanese Yen",
    feed: 12,
    ticker: "GBXJPY",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: "Turkish Lira/South African Rand Cents",
    feed: 12,
    ticker: "TRYZAC",
    isin: null,
    mic: null,
    currency: "ZAC",
  },
  {
    fullName: "Czech Koruna / Japanese Yen",
    feed: 12,
    ticker: "CZKJPY",
    isin: null,
    mic: null,
    currency: "JPY",
  },
  {
    fullName: "Swedish Krona / Brazilian Real",
    feed: 12,
    ticker: "SEKBRL",
    isin: null,
    mic: null,
    currency: "BRL",
  },
  {
    fullName: "Danish Krone / Icelandic Krone",
    feed: 12,
    ticker: "DKKISK",
    isin: null,
    mic: null,
    currency: "ISK",
  },
  {
    fullName: "Canadian Dollar / Turkish Lira",
    feed: 12,
    ticker: "CADTRY",
    isin: null,
    mic: null,
    currency: "TRY",
  },
  {
    fullName: "Swiss Franc/South African Rand Cents",
    feed: 12,
    ticker: "CHFZAC",
    isin: null,
    mic: null,
    currency: "ZAC",
  },
  {
    fullName: "Turkish Lira / Canadian Dollar",
    feed: 12,
    ticker: "TRYCAD",
    isin: null,
    mic: null,
    currency: "CAD",
  },
  {
    fullName: "Mexican Peso / Japanese Yen",
    feed: 12,
    ticker: "MXNJPY",
    isin: null,
    mic: null,
    currency: "JPY",
  },
  {
    fullName: "South African Rand / Icelandic Krone",
    feed: 12,
    ticker: "ZARISK",
    isin: null,
    mic: null,
    currency: "ISK",
  },
  {
    fullName: "New Zealand Dollar / Singapore Dollar",
    feed: 12,
    ticker: "NZDSGD",
    isin: null,
    mic: null,
    currency: "SGD",
  },
  {
    fullName: "Icelandic Krone / Norwegian Krone",
    feed: 12,
    ticker: "ISKNOK",
    isin: null,
    mic: null,
    currency: "NOK",
  },
  {
    fullName: "Brasilian Real / Danish Krone",
    feed: 12,
    ticker: "BRLDKK",
    isin: null,
    mic: null,
    currency: "DKK",
  },
  {
    fullName: "Thai Bath / Swedish Krona",
    feed: 12,
    ticker: "THBSEK",
    isin: null,
    mic: null,
    currency: "SEK",
  },
  {
    fullName: "Swiss Franc / South African Rand",
    feed: 12,
    ticker: "CHFZAR",
    isin: null,
    mic: null,
    currency: "ZAR",
  },
  {
    fullName: "Japanese Yen / South Africa Rand",
    feed: 12,
    ticker: "JPYZAR",
    isin: null,
    mic: null,
    currency: "ZAR",
  },
  {
    fullName: "Japanese Yen / Kenyan Shilling",
    feed: 12,
    ticker: "JPYKES",
    isin: null,
    mic: null,
    currency: "KES",
  },
  {
    fullName: "Japanese Yen/US Dollar",
    feed: 12,
    ticker: "JPYUSD",
    isin: null,
    mic: null,
    currency: "USD",
  },
  {
    fullName: "British Pence / Czech Koruna",
    feed: 12,
    ticker: "GBXCZK",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: "Polish Zloty / Danish Krone",
    feed: 12,
    ticker: "PLNDKK",
    isin: null,
    mic: null,
    currency: "DKK",
  },
  {
    fullName: "South African Rand / Swedish Krona",
    feed: 12,
    ticker: "ZARSEK",
    isin: null,
    mic: null,
    currency: "SEK",
  },
  {
    fullName: "Mexian Peso / Czech Kronua",
    feed: 12,
    ticker: "MXNCZK",
    isin: null,
    mic: null,
    currency: "CZK",
  },
  {
    fullName: "Brazilian Real / Swedish Krona",
    feed: 12,
    ticker: "BRLSEK",
    isin: null,
    mic: null,
    currency: "SEK",
  },
  {
    fullName: "South African Rand / Mauritian Rupee",
    feed: 12,
    ticker: "ZARMUR",
    isin: null,
    mic: null,
    currency: "MUR",
  },
  {
    fullName: "British Pence / Singapore Dollar",
    feed: 12,
    ticker: "GBXSGD",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: "Brazilian Real/South African Rand",
    feed: 12,
    ticker: "BRLZAR",
    isin: null,
    mic: null,
    currency: "ZAR",
  },
  {
    fullName: "Canadian Dollar / South African Rand",
    feed: 12,
    ticker: "CADZAR",
    isin: null,
    mic: null,
    currency: "ZAR",
  },
  {
    fullName: "Canadian Dollar / Kenyan Shilling",
    feed: 12,
    ticker: "CADKES",
    isin: null,
    mic: null,
    currency: "KES",
  },
  {
    fullName: "Brazilian Real / Icelandic Krone",
    feed: 12,
    ticker: "BRLISK",
    isin: null,
    mic: null,
    currency: "ISK",
  },
  {
    fullName: "Hong Kong Dollar / Polish Zloty",
    feed: 12,
    ticker: "HKDPLN",
    isin: null,
    mic: null,
    currency: "PLN",
  },
  {
    fullName: "Chinese Yuan / South African Rand",
    feed: 12,
    ticker: "CNYZAR",
    isin: null,
    mic: null,
    currency: "ZAR",
  },
  {
    fullName: "Hungarian Rongit/US Dollar",
    feed: 12,
    ticker: "HUFUSD",
    isin: null,
    mic: null,
    currency: "USD",
  },
  {
    fullName: "British Pence / Australian Dollar",
    feed: 12,
    ticker: "GBXAUD",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: "British Pence / Swedish Krona",
    feed: 12,
    ticker: "GBXSEK",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: "South African Rand / Botswana Pula",
    feed: 12,
    ticker: "ZARBWP",
    isin: null,
    mic: null,
    currency: "BWP",
  },
  {
    fullName: "US Dollar/Belarusian Ruble",
    feed: 12,
    ticker: "USDBYR",
    isin: null,
    mic: null,
    currency: "BYR",
  },
  {
    fullName: "South African Rand / Japanese Yen",
    feed: 12,
    ticker: "ZARJPY",
    isin: null,
    mic: null,
    currency: "JPY",
  },
  {
    fullName: "British Pence / Norwegian Krone",
    feed: 12,
    ticker: "GBXNOK",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: "British Pence / Canadian Dollar",
    feed: 12,
    ticker: "GBXCAD",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: "British Pence / Danish Krona",
    feed: 12,
    ticker: "GBXDKK",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: "British Pence / US Dollar",
    feed: 12,
    ticker: "GBXUSD",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: "British Pound / Mexican Peso",
    feed: 12,
    ticker: "GBPMXN",
    isin: null,
    mic: null,
    currency: "MXN",
  },
  {
    fullName: "Canadian Dollar / Nigarian Naira",
    feed: 12,
    ticker: "CADNGN",
    isin: null,
    mic: null,
    currency: "NGN",
  },
  {
    fullName: "Hungarian Forint/Euro",
    feed: 12,
    ticker: "HUFEUR",
    isin: null,
    mic: null,
    currency: "EUR",
  },
  {
    fullName: "British Pence / South African Rand",
    feed: 12,
    ticker: "GBXZAR",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: "Indian Rupee / Danish Krona",
    feed: 12,
    ticker: "INRDKK",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: "Euro / Nigarian Naira",
    feed: 12,
    ticker: "EURNGN",
    isin: null,
    mic: null,
    currency: "NGN",
  },
  {
    fullName: "British Pence / Turkish Lira",
    feed: 12,
    ticker: "GBXTRY",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: "British Pound / Indian Rupee",
    feed: 12,
    ticker: "GBPINR",
    isin: null,
    mic: null,
    currency: "INR",
  },
  {
    fullName: "Taiwan Dollar / US Dollar",
    feed: 12,
    ticker: "TWDUSD",
    isin: null,
    mic: null,
    currency: "USD",
  },
  {
    fullName: "British Pence / Euro",
    feed: 12,
    ticker: "GBXEUR",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: "Vietnam Dong / US Dollar",
    feed: 12,
    ticker: "VNDUSD",
    isin: null,
    mic: null,
    currency: "USD",
  },
  {
    fullName: "British Pound / Nigarian Naira",
    feed: 12,
    ticker: "GBPNGN",
    isin: null,
    mic: null,
    currency: "NGN",
  },
  {
    fullName: "Swedish TCW Index",
    feed: 12,
    ticker: "TCWINDEX",
    isin: null,
    mic: null,
    currency: "SEK",
  },
  {
    fullName: "Polish Zloty / Icelandic Krone",
    feed: 12,
    ticker: "PLNISK",
    isin: null,
    mic: null,
    currency: "ISK",
  },
  {
    fullName: "Chinese Yuan / Danish Krone",
    feed: 12,
    ticker: "CNYDKK",
    isin: null,
    mic: null,
    currency: "DKK",
  },
  {
    fullName: "Swiss Franc / Hungarian Forint",
    feed: 12,
    ticker: "CHFHUF",
    isin: null,
    mic: null,
    currency: "HUF",
  },
  {
    fullName: "Kenyan Shilling / Euro",
    feed: 12,
    ticker: "KESEUR",
    isin: null,
    mic: null,
    currency: "EUR",
  },
  {
    fullName: "South African Rand / Hong Kong Dollar",
    feed: 12,
    ticker: "ZARHKD",
    isin: null,
    mic: null,
    currency: "HKD",
  },
  {
    fullName: "South African Rand / Kenyan Shilling",
    feed: 12,
    ticker: "ZARKES",
    isin: null,
    mic: null,
    currency: "KES",
  },
  {
    fullName: "Japanese Yen / Polish Zloty",
    feed: 12,
    ticker: "JPYPLN",
    isin: null,
    mic: null,
    currency: "PLN",
  },
  {
    fullName: "Mauritian Rupee / South African Rand",
    feed: 12,
    ticker: "MURZAR",
    isin: null,
    mic: null,
    currency: "ZAR",
  },
  {
    fullName: "Saudi Arabian Riyal / Icelandic Krone",
    feed: 12,
    ticker: "SARISK",
    isin: null,
    mic: null,
    currency: "ISK",
  },
  {
    fullName: "South African Rand / Brasilian Real",
    feed: 12,
    ticker: "ZARBRL",
    isin: null,
    mic: null,
    currency: "BRL",
  },
  {
    fullName: "British Pence / Swiss Franc",
    feed: 12,
    ticker: "GBXCHF",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: "Kenyan Shiliing / British Pound",
    feed: 12,
    ticker: "KESGBP",
    isin: null,
    mic: null,
    currency: "GBP",
  },
  {
    fullName: "British Pence / Nigerian Naira",
    feed: 12,
    ticker: "GBXNGN",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 12,
    ticker: "EURLVL",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 12,
    ticker: "USDLVL",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 12,
    ticker: "GBXGBP",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 12,
    ticker: "GBPGBX",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 12,
    ticker: "AUDISK",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 12,
    ticker: "EUREEK",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 12,
    ticker: "EURLTL",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 12,
    ticker: "USDLTL",
    isin: null,
    mic: null,
    currency: null,
  },
];
