export const DENMARK_TICKERS = [
  "CPHCAP PREF",
  "SWISS",
  "OMXCMCGI",
  "KBHL",
  "CX201020GI",
  "SAME",
  "SLXIT",
  "MOVINN",
  "CX3010GI",
  "KONSOL",
  "CX45PI",
  "CX201030GI",
  "CX151010PI",
  "SOLAR B",
  "GYLD B",
  "LUXOR B",
  "FLUG B",
  "CX10PI",
  "CX4020GI",
  "KRE",
  "CX502020GI",
  "CX402040PI",
  "CX502050GI",
  "OMXC25ESGNI",
  "AAB",
  "KLEE B",
  "CX451030PI",
  "CX451020PI",
  "SIG",
  "OMXCSCPI",
  "CX50PI",
  "BO",
  "CHR",
  "OMXCLCGI",
  "GREENM",
  "CX45GI",
  "ALEFRM",
  "OMXC25GI",
  "EGNETY",
  "GABR",
  "DFDS",
  "DSV",
  "NORTHM",
  "MDUNDO",
  "SIM",
  "STENO TO 1",
  "OMXCBCAPGI",
  "XACTC25",
  "NOVO B",
  "QINTER",
  "NEWCAP",
  "OMXCBGI",
  "VWS",
  "RBLN B",
  "GYLD A",
  "OMXCBPI",
  "CX35GI",
  "JDAN",
  "CX502030GI",
  "FFARMS",
  "FLS",
  "NZYM B",
  "HH",
  "CX50GI",
  "STENO TO 2",
  "CHEMM",
  "BNORDIK CSE",
  "CX40PI",
  "VJBA",
  "OMXCSCGI",
  "CX65GI",
  "ORSTED",
  "DEMANT",
  "BIF",
  "CX5520GI",
  "PENNEO",
  "CEMAT",
  "CX201020PI",
  "GJ",
  "DJUR",
  "OMXC25ESG",
  "STRINV",
  "NKT",
  "SPNO",
  "CX303020PI",
  "GRLA",
  "BIOPOR",
  "VIRO",
  "TRIFOR",
  "CX10GI",
  "BRAINP",
  "SMSMED",
  "ROCK A",
  "WMA",
  "HRC",
  "CX404010GI",
  "SBS",
  "DONKEY",
  "TGAMES",
  "CX30GI",
  "AOJ B",
  "CX451010PI",
  "ZEAL",
  "NORDIC",
  "CX101020GI",
  "DANSKE",
  "ODICO",
  "FOM",
  "RILBA",
  "GUBRA",
  "CX4510PI",
  "MTHH",
  "FED",
  "CX5520PI",
  "WIRTEK",
  "CX35PI",
  "CX351020PI",
  "OMXC25",
  "CX502060PI",
  "TCM",
  "FASTPC",
  "PNDORA",
  "ALK B",
  "CX4010GI",
  "OMXCXC20GI",
  "CX3020PI",
  "SHAPE",
  "CPHCAP PREF32",
  "MONSO",
  "OMXCXC20PI",
  "TRMD A",
  "CX201030PI",
  "ROCK B",
  "HART",
  "CX502040PI",
  "CX4050PI",
  "CX502050PI",
  "TIV",
  "CX351010PI",
  "BOOZT DKK",
  "CX40GI",
  "PRIMOF",
  "COLO B",
  "NLFSK",
  "STG",
  "SKAKO",
  "CX30PI",
  "CX302020PI",
  "NEXCOM",
  "CX502040GI",
  "OMXC25ESGGI",
  "NNIT",
  "CBRAIN",
  "CX601020GI",
  "CX101020PI",
  "CX20PI",
  "CX402020GI",
  "CX4040GI",
  "ISS",
  "DAC",
  "CX15GI",
  "PEG",
  "AGAT",
  "CX4020PI",
  "SAS DKK",
  "GN",
  "SIF",
  "LOLB",
  "SPENN",
  "ATLA DKK",
  "DNORD",
  "ODICO T",
  "OMXCCAPGI",
  "SCHO",
  "RBREW",
  "BACTIQ",
  "MAPS",
  "BRAINP TO3",
  "FYNBK",
  "YOYO",
  "CX402040GI",
  "ESG",
  "NRDF",
  "CX651010PI",
  "NTG",
  "CX4510GI",
  "OMXCPI",
  "CX101010PI",
  "OMXCCAPPI",
  "CX4010PI",
  "RELE",
  "LASP",
  "CX101010GI",
  "MAERSK A",
  "CX15PI",
  "RISMA",
  "HOVE",
  "CX60PI",
  "SPG",
  "PARKST A",
  "CPHCAP ST",
  "RTX",
  "CARL B",
  "IMPERO",
  "EAC",
  "AGF B",
  "CX601010PI",
  "STENO",
  "CX3020GI",
  "OMXC20GI",
  "DAB",
  "CX404010PI",
  "HUSCO",
  "NOBLE",
  "HVID",
  "AQP",
  "CX5020PI",
  "ASTRLS",
  "CX20GI",
  "OMXC20",
  "SPKSJF",
  "CX4040PI",
  "NTR B",
  "PARKEN",
  "AGILC",
  "HYPE",
  "OMXCMCPI",
  "CX502020PI",
  "AMBU B",
  "CX5010GI",
  "HYDRCT",
  "CX351010GI",
  "CX3010PI",
  "CX351020GI",
  "OMXCBCAPPI",
  "ALMB",
  "NORD",
  "CONFRZ",
  "OSSR",
  "CX303020GI",
  "CX5020GI",
  "UIE",
  "SKJE",
  "CX402030PI",
  "CX402020PI",
  "MAERSK B",
  "CX4030GI",
  "CX302020GI",
  "CX5010PI",
  "JYSK",
  "CBM",
  "CX151010GI",
  "CX3030GI",
  "GERHSP",
  "ACT",
  "CX502030PI",
  "TOP",
  "TRYG",
  "IMAIL",
  "CARL A",
  "CX502060GI",
  "MNBA",
  "HLUN A",
  "LEDIBOND",
  "HLUN B",
  "HARB B",
  "CX651010GI",
  "DATA",
  "CX451030GI",
  "NETC",
  "CX451020GI",
  "CX451010GI",
  "OMXC25EXP",
  "CX402030GI",
  "NDA DK",
  "ERRIA",
  "GREENH",
  "ORPHA",
  "SYDB",
  "CX4030PI",
  "OMXC25NI",
  "CX4050GI",
  "CX601010GI",
  "OMXCGI",
  "GMAB",
  "PAAL B",
  "ASTK",
  "CX65PI",
  "MATAS",
  "BAVA",
  "OMXCNI",
  "CX3030PI",
  "ROV",
  "CX60GI",
  "RIAS B",
  "OMXCLCPI",
  "SCAPE",
  "OMXC25DVP",
  "CX601020PI",
  "COLUM",
  "DANT",
];

export const DENMARK_FEED = [
  {
    fullName: null,
    feed: 17665,
    ticker: "CPHCAP PREF",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 17665,
    ticker: "SWISS",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 17665,
    ticker: "OMXCMCGI",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 17665,
    ticker: "KBHL",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 17665,
    ticker: "CX201020GI",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 17665,
    ticker: "SAME",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 17665,
    ticker: "SLXIT",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 17665,
    ticker: "MOVINN",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 17665,
    ticker: "CX3010GI",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 17665,
    ticker: "KONSOL",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 17665,
    ticker: "CX45PI",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 17665,
    ticker: "CX201030GI",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 17665,
    ticker: "CX151010PI",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 17665,
    ticker: "SOLAR B",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 17665,
    ticker: "GYLD B",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 17665,
    ticker: "LUXOR B",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 17665,
    ticker: "FLUG B",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 17665,
    ticker: "CX10PI",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 17665,
    ticker: "CX4020GI",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 17665,
    ticker: "KRE",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 17665,
    ticker: "CX502020GI",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 17665,
    ticker: "CX402040PI",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 17665,
    ticker: "CX502050GI",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 17665,
    ticker: "OMXC25ESGNI",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 17665,
    ticker: "AAB",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 17665,
    ticker: "KLEE B",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 17665,
    ticker: "CX451030PI",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 17665,
    ticker: "CX451020PI",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 17665,
    ticker: "SIG",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 17665,
    ticker: "OMXCSCPI",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 17665,
    ticker: "CX50PI",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 17665,
    ticker: "BO",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 17665,
    ticker: "CHR",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 17665,
    ticker: "OMXCLCGI",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 17665,
    ticker: "GREENM",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 17665,
    ticker: "CX45GI",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 17665,
    ticker: "ALEFRM",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 17665,
    ticker: "OMXC25GI",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 17665,
    ticker: "EGNETY",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 17665,
    ticker: "GABR",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 17665,
    ticker: "DFDS",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 17665,
    ticker: "DSV",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 17665,
    ticker: "NORTHM",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 17665,
    ticker: "MDUNDO",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 17665,
    ticker: "SIM",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 17665,
    ticker: "STENO TO 1",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 17665,
    ticker: "OMXCBCAPGI",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 17665,
    ticker: "XACTC25",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 17665,
    ticker: "NOVO B",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 17665,
    ticker: "QINTER",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 17665,
    ticker: "NEWCAP",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 17665,
    ticker: "OMXCBGI",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 17665,
    ticker: "VWS",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 17665,
    ticker: "RBLN B",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 17665,
    ticker: "GYLD A",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 17665,
    ticker: "OMXCBPI",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 17665,
    ticker: "CX35GI",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 17665,
    ticker: "JDAN",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 17665,
    ticker: "CX502030GI",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 17665,
    ticker: "FFARMS",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 17665,
    ticker: "FLS",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 17665,
    ticker: "NZYM B",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 17665,
    ticker: "HH",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 17665,
    ticker: "CX50GI",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 17665,
    ticker: "STENO TO 2",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 17665,
    ticker: "CHEMM",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 17665,
    ticker: "BNORDIK CSE",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 17665,
    ticker: "CX40PI",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 17665,
    ticker: "VJBA",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 17665,
    ticker: "OMXCSCGI",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 17665,
    ticker: "CX65GI",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 17665,
    ticker: "ORSTED",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 17665,
    ticker: "DEMANT",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 17665,
    ticker: "BIF",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 17665,
    ticker: "CX5520GI",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 17665,
    ticker: "PENNEO",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 17665,
    ticker: "CEMAT",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 17665,
    ticker: "CX201020PI",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 17665,
    ticker: "GJ",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 17665,
    ticker: "DJUR",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 17665,
    ticker: "OMXC25ESG",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 17665,
    ticker: "STRINV",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 17665,
    ticker: "NKT",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 17665,
    ticker: "SPNO",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 17665,
    ticker: "CX303020PI",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 17665,
    ticker: "GRLA",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 17665,
    ticker: "BIOPOR",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 17665,
    ticker: "VIRO",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 17665,
    ticker: "TRIFOR",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 17665,
    ticker: "CX10GI",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 17665,
    ticker: "BRAINP",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 17665,
    ticker: "SMSMED",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 17665,
    ticker: "ROCK A",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 17665,
    ticker: "WMA",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 17665,
    ticker: "HRC",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 17665,
    ticker: "CX404010GI",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 17665,
    ticker: "SBS",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 17665,
    ticker: "DONKEY",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 17665,
    ticker: "TGAMES",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 17665,
    ticker: "CX30GI",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 17665,
    ticker: "AOJ B",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 17665,
    ticker: "CX451010PI",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 17665,
    ticker: "ZEAL",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 17665,
    ticker: "NORDIC",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 17665,
    ticker: "CX101020GI",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 17665,
    ticker: "DANSKE",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 17665,
    ticker: "ODICO",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 17665,
    ticker: "FOM",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 17665,
    ticker: "RILBA",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 17665,
    ticker: "GUBRA",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 17665,
    ticker: "CX4510PI",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 17665,
    ticker: "MTHH",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 17665,
    ticker: "FED",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 17665,
    ticker: "CX5520PI",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 17665,
    ticker: "WIRTEK",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 17665,
    ticker: "CX35PI",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 17665,
    ticker: "CX351020PI",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 17665,
    ticker: "OMXC25",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 17665,
    ticker: "CX502060PI",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 17665,
    ticker: "TCM",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 17665,
    ticker: "FASTPC",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 17665,
    ticker: "PNDORA",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 17665,
    ticker: "ALK B",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 17665,
    ticker: "CX4010GI",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 17665,
    ticker: "OMXCXC20GI",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 17665,
    ticker: "CX3020PI",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 17665,
    ticker: "SHAPE",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 17665,
    ticker: "CPHCAP PREF32",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 17665,
    ticker: "MONSO",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 17665,
    ticker: "OMXCXC20PI",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 17665,
    ticker: "TRMD A",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 17665,
    ticker: "CX201030PI",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 17665,
    ticker: "ROCK B",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 17665,
    ticker: "HART",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 17665,
    ticker: "CX502040PI",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 17665,
    ticker: "CX4050PI",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 17665,
    ticker: "CX502050PI",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 17665,
    ticker: "TIV",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 17665,
    ticker: "CX351010PI",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 17665,
    ticker: "BOOZT DKK",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 17665,
    ticker: "CX40GI",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 17665,
    ticker: "PRIMOF",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 17665,
    ticker: "COLO B",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 17665,
    ticker: "NLFSK",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 17665,
    ticker: "STG",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 17665,
    ticker: "SKAKO",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 17665,
    ticker: "CX30PI",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 17665,
    ticker: "CX302020PI",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 17665,
    ticker: "NEXCOM",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 17665,
    ticker: "CX502040GI",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 17665,
    ticker: "OMXC25ESGGI",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 17665,
    ticker: "NNIT",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 17665,
    ticker: "CBRAIN",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 17665,
    ticker: "CX601020GI",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 17665,
    ticker: "CX101020PI",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 17665,
    ticker: "CX20PI",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 17665,
    ticker: "CX402020GI",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 17665,
    ticker: "CX4040GI",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 17665,
    ticker: "ISS",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 17665,
    ticker: "DAC",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 17665,
    ticker: "CX15GI",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 17665,
    ticker: "PEG",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 17665,
    ticker: "AGAT",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 17665,
    ticker: "CX4020PI",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 17665,
    ticker: "SAS DKK",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 17665,
    ticker: "GN",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 17665,
    ticker: "SIF",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 17665,
    ticker: "LOLB",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 17665,
    ticker: "SPENN",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 17665,
    ticker: "ATLA DKK",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 17665,
    ticker: "DNORD",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 17665,
    ticker: "ODICO T",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 17665,
    ticker: "OMXCCAPGI",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 17665,
    ticker: "SCHO",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 17665,
    ticker: "RBREW",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 17665,
    ticker: "BACTIQ",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 17665,
    ticker: "MAPS",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 17665,
    ticker: "BRAINP TO3",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 17665,
    ticker: "FYNBK",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 17665,
    ticker: "YOYO",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 17665,
    ticker: "CX402040GI",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 17665,
    ticker: "ESG",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 17665,
    ticker: "NRDF",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 17665,
    ticker: "CX651010PI",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 17665,
    ticker: "NTG",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 17665,
    ticker: "CX4510GI",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 17665,
    ticker: "OMXCPI",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 17665,
    ticker: "CX101010PI",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 17665,
    ticker: "OMXCCAPPI",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 17665,
    ticker: "CX4010PI",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 17665,
    ticker: "RELE",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 17665,
    ticker: "LASP",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 17665,
    ticker: "CX101010GI",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 17665,
    ticker: "MAERSK A",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 17665,
    ticker: "CX15PI",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 17665,
    ticker: "RISMA",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 17665,
    ticker: "HOVE",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 17665,
    ticker: "CX60PI",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 17665,
    ticker: "SPG",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 17665,
    ticker: "PARKST A",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 17665,
    ticker: "CPHCAP ST",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 17665,
    ticker: "RTX",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 17665,
    ticker: "CARL B",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 17665,
    ticker: "IMPERO",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 17665,
    ticker: "EAC",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 17665,
    ticker: "AGF B",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 17665,
    ticker: "CX601010PI",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 17665,
    ticker: "STENO",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 17665,
    ticker: "CX3020GI",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 17665,
    ticker: "OMXC20GI",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 17665,
    ticker: "DAB",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 17665,
    ticker: "CX404010PI",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 17665,
    ticker: "HUSCO",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 17665,
    ticker: "NOBLE",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 17665,
    ticker: "HVID",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 17665,
    ticker: "AQP",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 17665,
    ticker: "CX5020PI",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 17665,
    ticker: "ASTRLS",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 17665,
    ticker: "CX20GI",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 17665,
    ticker: "OMXC20",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 17665,
    ticker: "SPKSJF",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 17665,
    ticker: "CX4040PI",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 17665,
    ticker: "NTR B",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 17665,
    ticker: "PARKEN",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 17665,
    ticker: "AGILC",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 17665,
    ticker: "HYPE",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 17665,
    ticker: "OMXCMCPI",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 17665,
    ticker: "CX502020PI",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 17665,
    ticker: "AMBU B",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 17665,
    ticker: "CX5010GI",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 17665,
    ticker: "HYDRCT",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 17665,
    ticker: "CX351010GI",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 17665,
    ticker: "CX3010PI",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 17665,
    ticker: "CX351020GI",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 17665,
    ticker: "OMXCBCAPPI",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 17665,
    ticker: "ALMB",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 17665,
    ticker: "NORD",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 17665,
    ticker: "CONFRZ",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 17665,
    ticker: "OSSR",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 17665,
    ticker: "CX303020GI",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 17665,
    ticker: "CX5020GI",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 17665,
    ticker: "UIE",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 17665,
    ticker: "SKJE",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 17665,
    ticker: "CX402030PI",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 17665,
    ticker: "CX402020PI",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 17665,
    ticker: "MAERSK B",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 17665,
    ticker: "CX4030GI",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 17665,
    ticker: "CX302020GI",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 17665,
    ticker: "CX5010PI",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 17665,
    ticker: "JYSK",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 17665,
    ticker: "CBM",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 17665,
    ticker: "CX151010GI",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 17665,
    ticker: "CX3030GI",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 17665,
    ticker: "GERHSP",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 17665,
    ticker: "ACT",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 17665,
    ticker: "CX502030PI",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 17665,
    ticker: "TOP",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 17665,
    ticker: "TRYG",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 17665,
    ticker: "IMAIL",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 17665,
    ticker: "CARL A",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 17665,
    ticker: "CX502060GI",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 17665,
    ticker: "MNBA",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 17665,
    ticker: "HLUN A",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 17665,
    ticker: "LEDIBOND",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 17665,
    ticker: "HLUN B",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 17665,
    ticker: "HARB B",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 17665,
    ticker: "CX651010GI",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 17665,
    ticker: "DATA",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 17665,
    ticker: "CX451030GI",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 17665,
    ticker: "NETC",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 17665,
    ticker: "CX451020GI",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 17665,
    ticker: "CX451010GI",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 17665,
    ticker: "OMXC25EXP",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 17665,
    ticker: "CX402030GI",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 17665,
    ticker: "NDA DK",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 17665,
    ticker: "ERRIA",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 17665,
    ticker: "GREENH",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 17665,
    ticker: "ORPHA",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 17665,
    ticker: "SYDB",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 17665,
    ticker: "CX4030PI",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 17665,
    ticker: "OMXC25NI",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 17665,
    ticker: "CX4050GI",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 17665,
    ticker: "CX601010GI",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 17665,
    ticker: "OMXCGI",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 17665,
    ticker: "GMAB",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 17665,
    ticker: "PAAL B",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 17665,
    ticker: "ASTK",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 17665,
    ticker: "CX65PI",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 17665,
    ticker: "MATAS",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 17665,
    ticker: "BAVA",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 17665,
    ticker: "OMXCNI",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 17665,
    ticker: "CX3030PI",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 17665,
    ticker: "ROV",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 17665,
    ticker: "CX60GI",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 17665,
    ticker: "RIAS B",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 17665,
    ticker: "OMXCLCPI",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 17665,
    ticker: "SCAPE",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 17665,
    ticker: "OMXC25DVP",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 17665,
    ticker: "CX601020PI",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 17665,
    ticker: "COLUM",
    isin: null,
    mic: null,
    currency: null,
  },
  {
    fullName: null,
    feed: 17665,
    ticker: "DANT",
    isin: null,
    mic: null,
    currency: null,
  },
];
